### ISSUE TITLE
Specify reloading current page

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#106]
CDP has [Page.reload](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-reload). Seems like a reasonable place to start. Difference from `Page.navigate` with transition type set to reload? Presumably have the same `wait` arguments as navigation.

**Comment by foolip** [comment]
I don't know what CDP looks like here, but https://github.com/puppeteer/puppeteer/blob/v9.1.1/docs/api.md#pagereloadoptions does have the same `waitUntil` options.

**Comment by whimboo** [comment]
The reload command landed via PR #107.
