### ISSUE TITLE
Specify creating/opening a browsing context

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#116]
Before one can [navigate](https://github.com/w3c/webdriver-bidi/issues/43) a browsing context, one has to be able to open one.

**Comment by whimboo** [comment]
When the browser gets started there is always a default tab open, which implies that also a top-level browsing context (navigable) exists. When the last tab gets closed, the session automatically ends and the browser quits. So under which condition do we have to block the navigation? Isn't it just that we have to retrieve the current or a list of known to be open browsing contexts?

**Comment by jgraham** [comment]
I think the concern is that if one doesn't specify how to create a browsing context, one can't be _sure_ it already exists. Nothing really requires browsers to open a context at startup.

In practice a) browsers always do create a context at startup, so it's hard to get into a situation where there isn't one and b) we do need this feature for the same reasons we needed it in WebDriver classic. So I don't think we need to block on it but I also don't think we want to delay it too mcuh given it's not complex.

**Comment by whimboo** [comment]
> I think the concern is that if one doesn't specify how to create a browsing context, one can't be _sure_ it already exists. Nothing really requires browsers to open a context at startup.

Sure but there is [browsingContext.getTree()](https://w3c.github.io/webdriver-bidi/#command-browsingContext-getTree) to get the list of open browsing contexts. Maybe we also just need a command to return the currently active navigable / browsing context.

**Comment by foolip** [comment]
My concern stems from the fact that most Puppeteer examples one can find all open a new page and navigate it, rather than finding the already open page and using that. It's true that this doesn't block https://github.com/w3c/webdriver-bidi/issues/43, but it seems like something we want sooner rather than later.

Even with such a command, it would still be good to specify that there should be exactly one browsing context for a new session, if we want clients to be able to depend on that and not waste that browsing context.

**Comment by jgraham** [comment]
We could speccify that there must be at least one browsing context at session creation, but we can't specify that there must be exactly one (consider connecting to an already running browser, or a tool that does passive monitoring of network traffic and rendering timing for performance analysis. rather than driving tests itself).

**Comment by foolip** [comment]
At least one would do then :)
