### ISSUE TITLE
Specify closing a top-level browsing context

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#117]
AKA "navigable".

**Comment by Lightning00Blade** [comment]
@jgraham, closing as I believe this was done in https://github.com/w3c/webdriver-bidi/issues/170 ([comment](https://github.com/w3c/webdriver-bidi/issues/170#issuecomment-1025754967) says only top-level should be allowed.) and merged via https://github.com/w3c/webdriver-bidi/pull/172.
