### ISSUE TITLE
Specify closing the browser.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#119]
There should be a way to close the browser (and thereby terminate the session). c.f. https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-close

**Comment by sadym-chromium** [comment]
If we decide not to allow reconnections, closing or dropping connection would mean the browser should be closed. 

Options described here: [#25 ](https://github.com/w3c/webdriver-bidi/issues/25#issuecomment-643189522)

**Comment by jgraham** [comment]
I think we definitely want to support reconnection to an existing session; that was a request that came from clients and is pretty much already supported in the spec. Also, ending the session shouldn't necessarily close the browser; it makes more sense to build "end session" and "close browser" as separate primitives. Automation tools may have more cases where they close the browser and thereby implicitly end all sessions, but it still makes sense to seperate concerns.

**Comment by OrKoN** [comment]
Puppeteer is using this method and we will need it eventually to offer the same API. Currently, we use `Browser.close` for remote connections only. If the browser process is running locally, we kill the process.

**Comment by whimboo** [comment]
Note that force killing a process will NOT shutdown the browser cleanly. A lot of shutdown steps that the browser usually runs will be skipped and data-loss might be involved. So having a clean method to close the browser from within the application itself should be much preferred.

**Comment by jgraham** [comment]
I think there's pretty much a conclusion in the discussion above, which is that if the command succeeds it will end all automation sessions and close all windows that were under automation, but it won't necessarily actually terminate the top-level browser process. If you want to do that you need to use os-level features (like signalling the top level process), which of course means that you're subject to whatever normal permissions checks the OS has.

All that's really required here is someone to write up the command.

**Comment by jgraham** [comment]
FWIW I think it should also be possible for the command to fail and end up just closing the actual session (e.g. that might be reasonable if you allow multiple automation sessions in a single browser instance and want to allow only the first session to actually have the ability to shut down the browser).

**Comment by whimboo** [comment]
The required work was done on https://github.com/w3c/webdriver-bidi/pull/286.
