### ISSUE TITLE
Transfer issues from other repo

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#13]
Let's transfer https://github.com/w3c/webdriver/labels/BiDi to this repo.

It looks like I have the ability to do it ([here's how](https://twitter.com/natfriedman/status/1057678371256119297)) but I want to ask first.

@jgraham @bwalderman @christian-bromann good idea?

**Comment by bwalderman** [comment]
Sounds good to me!

**Comment by jgraham** [comment]
Yes, I was planning to do this.

**Comment by jgraham** [comment]
Done.

**Comment by foolip** [comment]
I'll move the single closed one as well, https://github.com/w3c/webdriver/issues/1504.
