### ISSUE TITLE
Specify a low-level transport format

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#14]
The bi-directional protocol needs a low-level format for encoding messages that are sent over the wire.

The discussion so far has assumed that the format will be JSON-based; this has compatibility with the HTTP protocol and good human readability. It matches other existing protocols (although note that CDP now has a binary variant) and likely makes sense if we think that the message parsing overhead will be small compared to other latencies in the system.

@burg proposed that we adopt [JSON-RPC](https://www.jsonrpc.org/specification) as the specific flavour of JSON for the protocol. This meets several requirements:
* Provides a command type and a response type with an id field on match commands and responses
* Provides an event type that isn't generated by a command
* Provides an error type

However there are several details that might not match our requirements
* Requires a version number on every message, bloating the protocol for little gain (updating versions in WebDriver would be a difficult undertaking given the compatibility guarantees we provide).
* The protocol has a pipelining feature where an array of commands can be sent at once. This kind of feature seems useful to us, but the particular requirement that the implementation produce an array of responses doesn't seem like it matches use cases we might have (like running multiple concurrent commands and getting the response from each as soon as its ready).
* The spec has several SHOULD-level requirements; this is owrrying from the point of view of obtaining interop.

**Comment by foolip** [comment]
@jgraham we can consider this fixed now, right?

**Comment by jgraham** [comment]
Yes.
