### ISSUE TITLE
Events for the initial (temporary) about:blank document?

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#141]
With browsers coming up with site-isolation support to protect users against Spectre and Meltdown attacks, the navigation will become more complex due to unforeseen process switches during a navigation, which put pages into other browsing context groups. Also there is COOP, which does the same.

That said, the question that comes up now is how should we handle navigation events. Should we only send them out for the browsing context group of the target page or also for the initial about:blank page, which is initially loaded for a new window/tab (`window.open()`) or frame and then immediately replaced by the target page?

The navigation event mainly affected here is [browsingContext.load](https://w3c.github.io/webdriver-bidi/#event-browsingContext-load).

Would it be acceptable for the clients to receive the event twice, which would require them to check for the actual URL, or shall we only send the event at the very end of the navigation?

CC'ing @jgraham and @foolip.

**Comment by jgraham** [comment]
So AIUI there are two different issues here:
* COOP and site isolation means that we can end up switching processes / browsing context groups during navigation. Internally that will involve creating a new browsing context. I think the consensus there is we don't want to expose that at the moment, but really want to replace the browsing context id with a navigable id which is stable over such transitions once the HTML spec has the necessary primitives to describe this.
* When creating a browsing context, there's an initial `about:blank` document. Historically interop around this document has been poor. For BiDi we could either choose to emit events relating to this document, which would be strictly correct, but might be confusing and likely to expose implementation differences, or we could suppress events relating to this document, which might be confusing in the case where the `about:blank` document is actually the final destination (e.g. if you `window.open` an empty page to run some script in).

I suggest we make this issue about the latter question, and use #91 for the question of stable identifiers.

**Comment by whimboo** [comment]
This issue is actually superseded by #766.
