### ISSUE TITLE
Behavior of log event buffer after calling unsubscribe

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#147]
Consider the following scenario, driving a test page with WebDriverBiDi:
- page executes `console.log("text1")`
- subscribe to `log.entryAdded`
- (a `log.entryAdded` event is generated for the buffered "text1" console.log)
- unsubscribe from `log.entryAdded`
- page executes `console.log("text2")`
- (no `log.entryAdded` event is generated for now)
- we subscribe again to `log.entryAdded`

What should happen at this point? Should we emit a `log.entryAdded` event for the "text2" message?
After checking with @jgraham , the specification currently says we should emit the event. 

If events buffered when you are unsubscribed are emitted when you re-subscribe, I think it makes the behavior of `unsubscribe` odd. If you unsubscribed from those events explicitly for a period of time, it's probably because you were explicitly not interested in them.

I want to check whether we are ok with the current spec or if we think it needs an update:
- Should we emit all the events which were not yet emitted when you subscribe? (ie what the spec says)
- Or only emit buffered events the first time you subscribe to events? 
- Or add a property on the event to differentiate live events from buffered events?

**Comment by sadym-chromium** [comment]
> If events buffered when you are unsubscribed are emitted when you re-subscribe, I think it makes the behavior of `unsubscribe` odd. If you unsubscribed from those events explicitly for a period of time, it's probably because you were explicitly not interested in them.

I read the spec as "buffered events will be emitted before the command is finished". So to implement the described scenario, client should start listening to the events after the second `subscribe` is finished.

Otherwise the "init" state will e different from the state "init - subscribe - unsubscribe".

**Comment by jgraham** [comment]
To draw an analogy with devtools: if you open the console, view some log events, close the console, and reopen the console, would you expect reopening the console to show all the events between closing it and reopening it? I think you probably would, so I don't think that BiDi should be different. If you really don't care about the backfill you can always drop those in the client (e.g. using the timestamp on `log.entryAdded`).

**Comment by juliandescottes** [comment]
I agree that having a way to filter out the backfill should be enough. Timestamp sounds ok. I would slightly prefer something explicit, either be able to opt out of the backfill when subscribing, or a flag on backfill events. But if we can safely compare timestamps from the log events on the client, that should work.

I can close this for now.
