### ISSUE TITLE
Discussion: need for `browsingContext.findElement` command

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#150]
* Opinion 1 (lazy): `browsingContext.findElement` can be implemented using `script.evaluate` or `script.callFunction` and DOM API, as Puppeteer does. So there is no need in yet another syntax sugar command. 
* Opinion 2 (ergonomic): I assume finding element(s) is one of the most used features, and having something like [`DOM.querySelector`](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-querySelector) can be at least convenient.

**Comment by sadym-chromium** [comment]
I cannot add labels, but there should be: `browsingContext` and `question`

**Comment by foolip** [comment]
@AutomatedTester do you have the power to give @sadym-chromium write access to the repo? For labeling in this case, but he should also be able to review PRs I think.

**Comment by foolip** [comment]
What would it take to implement https://w3c.github.io/webdriver/#find-element and the other WebDriver classic endpoints with `script.evaluate` or `script.callFunction`? At a glance it looks trivial, but things rarely are.

**Comment by AutomatedTester** [comment]
it would appear that @sadym-chromium has already been invited

**Comment by sadym-chromium** [comment]
"This invitation has expired."

**Comment by AutomatedTester** [comment]
> What would it take to implement https://w3c.github.io/webdriver/#find-element and the other WebDriver classic endpoints with `script.evaluate` or `script.callFunction`? At a glance it looks trivial, but things rarely are.

We can probably do most of it as it was originally designed to use that. The things that we need to be aware of is keeping a map of elements found so we can handle `StaleElementException` well. We need to handle the case of finding elements from within a closed Shadow Root which I doubt `script.evaluate` will be able to do.

**Comment by jgraham** [comment]
I agree this isn't a high priority; it's effectively a higher level API over `script.evaluate` and `querySelector`, and Puppeteer implements find element in terms of a script, so it's not like there's some existing API we need to replicate.

The shadow DOM stuff is different, it still makes sense to have a way to get inside the shadow dom of a Node. But that could perhaps just be part of the serialization of Element (i.e. if we return an Element give the serialization a `shadowRoot` property that is either null or a reference to the shadow root).

Getting clarity on what the model is for interacting with platform types, particuarly DOM nodes, seems like the high priority work item here.

**Comment by whimboo** [comment]
See also the discussion on https://github.com/w3c/webdriver-bidi/issues/342 and the decision to leave the implementation up to the client by eg. calling `evaluate`.

@jgraham I think that we can close this issue?

**Comment by thiagowfx** [comment]
+1 this can be closed. Client can do it with either `script.evaluate` or `script.callFunction`.

x-ref: https://github.com/GoogleChromeLabs/chromium-bidi/pull/337

**Comment by jgraham** [comment]
Reopening this, since Selenium and WebdriverIO projects consider this a high priority for BiDi.

Do we have concrete examples of things that are blocked in those clients due to the absence of this feature? Generally it seems like one could implement most kinds of selectors using a preload script that runs in a client-specific sandbox e.g. 
```js
function findElement(type, selector) {
  return _findElement(type, selector, false)
}

function findElements(type, selector) {
  return _findElement(type, selector, true)
}

function _findElement(type, selector, all) {
  if (type == "css") {
    return findElementByCSS(selector, all);
  }
  throw new Error(`Unsupported type $(type)`)
}

findElementByCSS(selector, all) {
  let selectorFunction = all ? querySelector : querySelectorAll;
  return selectorFunction(selector);
}
```
and then to use it you just run `script.callFunction("(type, selector) => findElement(type, selector)", args=[type, selector], sandbox="webdriver-impl-sandbox")`. Obviously that's not quite as easy as running `browsingContext.findElement(type, selector)` but it does provide the kind of one-shot extensibility of locator strategies that people have previously requested for classic WebDriver (just add more locators types to your preload script). Are there locator strategies that _can't_ be implemented in terms of js functions, or where such an implementation is prohibitively difficult?

**Comment by shs96c** [comment]
Additionally, things like the accessibility tree aren't available to JS implementations, and may never be. Without a `find element` command, there's no way to extend Bidi to support this kind of element location.

**Comment by shs96c** [comment]
We also want visibility into shadow trees, even if the the shadow root is closed and can't be pierced by JS

**Comment by AutomatedTester** [comment]
If we move everything to be within `script.callFunction` we are running the risk of having to effectively moving all of the Selenium code into preloaded scripts. While this makes browser vendors lives easier it puts a lot of work onto client bindings to make things work and limits who can make clients. The nice thing about WebDriver classic is that it simplifies who can make clients and they can have their own opinions. In a everything is a callFunction world people need to build the correct things before they can even worry about their opinionated framework
The other issue is the scalability. In preloading every page with JS to do simple tasks we are going to be sending a lot to the browser on session load. This could make the session start times quite slow as they load things up before a navigation occurs. This will impact cloud providers but could really impact those trying to build their own grid infrastructure with underpowered machines which QA departments are likely to have.

**Comment by jimevans** [comment]
I am entirely against assuming everything can be shunted into `script.callFunction` or `script.evaluate`, and am unlikely to be convinced to change my mind on that subject. I note this for reasons of "reaching consensus" on spec matters. I've been playing with an idea, the explicit goals of which are as follows:

* Minimize round-trips from the local end to the remote end for locating elements
* Enable implementation of WebDriver Classic's element finding commands using this mechanism
* Embrace the flexibility allowed by non-WebDriver-based frameworks location mechanisms natively (cf. [Playwright](https://playwright.dev/docs/api/class-locator)) in the BiDi protocol

I'm in no way ready to formalize my ideas yet in a spec PR, and am entirely unqualified to write the spec prose that would be required to describe the following, but as a strawman argument, I'm envisioning a scheme something like the pseudo-CDDL spec definition below:

**Command Type**

    browsingContext.locateNodes = {
      method: "browsingContext.locateNodes",
      params: browsingContext.LocateNodesParameters
    }

    browsingContext.LocateNodesParameters = {
      context: browsingContext.BrowsingContext,
      ? startNode: script.RemoteNodeValue,
      locators: [ + browsingContext.Locator ]
    }

    browsingContext.Locator = (
      browsingContext.CssLocator /
      browsingContext.XPathLocator /
      browsingContext.TextLocator /
      browsingContext.JavaScriptLocator /
      browsingContext.FrameLocator /
      browsingContext.ShadowRootLocator /
      browsingContext.AccessibleRoleLocator /
      browsingContext.AccessibleNameLocator /
      browsingContext.NthLocator /
      browsingContext.AndLocator /
      browsingContext.OrLocator
    )

**Return Type**

    browsingContext.LocateNodesResult = {
      context: browsingContext.BrowsingContext,
      nodes: [ * script.RemoteNodeValue ].
    }

If `startNode` is omitted or null, the `documentElement` node of the specified `browsingContext` is used as the starting node.

In general, a `browsingContext.Locator` would generally look like:

    {
      "type": text,
      "value": *** <something goes here> ***
    }

The `type` property identifies the type of locator. For the `value` property, I am unsure what would go in there. In some cases (CSS selectors, XPath), `text` would be sufficient, but in others, like for JavaScript, something more complex is likely to be required.

The idea would be that one would pass an array of locators which the remote end would use to successively locate elements. The implementation would loop through the list of locators. The first locator returns a list of nodes. The second locator is evaluated with the each of the nodes in the list returned from the first locator as the context node, which returns another list of nodes. The third locator is evaluated with each of the nodes in second as the context node, and so on, until a final list of nodes is reached, each of which meets the conditions of all of the locators iteratively from 0 to length - 1.

Each of the `Locator` types will obviously need to be defined, and the list above is not exhaustive. An extension mechanism might be nice, but I haven't figured out how to make that work conceptually. As for the ones listed above, my thoughts are as follows:
* `CssLocator` and `XPathLocator` are self-explanatory
* `TextLocator` would find an element by its text content; there may well need to be options for whether using visible text only, like `InnerText` or including all text, like `textContent`, and whether to do a full or substring match, but in any case, the definition should be defined by these web primitives
* `JavaScriptLocator` takes a function definition that takes an element as an argument and returns an array of elements
* `FrameLocator` returns the `documentElement` node of a frame/iframe element
* `ShadowRootLocator` returns the equivalent of the `shadowRoot` property of the RemoteNodeValue
* `AccessibleRoleLocator` and `AccessibleNameLocator` would query the accessibility tree by role or name, respectively
* `NthLocator` returns the (0-based) nth value in the returned list of nodes
* `AndLocator` and `OrLocator` accept another `browserContext.Locator`, applying either an "and" or "or" condition to the returned nodes are either an intersection or a union, respectively, of the nodes returned by each locator.

While any (most? all?) of the above locators may be implementable solely using script, I believe there is value in providing them via the protocol directly. Error handling for the command would, of course, need to explicitly point out at which point in the locator chain the location failed. Returning an empty array for no nodes found matching the criteria is perfectly normal and acceptable.

Yes, this seems an incredibly complicated solution, but I can't think of an easier way to meet my three stated goals for having a "find elements" command in the protocol.

**Comment by OrKoN** [comment]
> Additionally, things like the accessibility tree aren't available to JS implementations, and may never be. Without a find element command, there's no way to extend Bidi to support this kind of element location.

In Puppeteer we use channels to get access to accessibility tree by other means if the selector is based on A11y tree information.

> Additionally, it allows other users to extend the command by providing their own implementation of browsingContext.Locator for their own remote end interpretation. As an example, a remote end that allows automation of iOS applications could create a locator type to locate an element using the iOS class chain, passing a structure with { "type": "iosclasschain", "value": "<whatever an iOS class chain query looks like>" }.

I wonder how non-web-browser requirements have to be reflected in the protocol? E.g., would desktop apps support CSS locators? how should they deal with realms and serialization of DOM objects? Do they event have DOM? Is it one of the primary use cases for WebDriver BiDi?

**Comment by jlipps** [comment]
👋 Appium maintainer here, just want to +1 what @shs96c, @jimevans, @AutomatedTester have said. While respecting the fat that the WebDriver BiDi working group's primary focus is and should be the web platform, the fact is that it's a good thing for there to be standardization in automation protocols more generally, even beyond the web. (I have a whole [argument to this effect](https://gist.github.com/jlipps/84533982d2a6ae0f6e2b298be9aa4cd6#appium-webdriver-should-form-the-basis-of-a-ui-automation-standard) if you want to get into the guts of a larger doc I wrote several years ago).

UI automation of app platforms is going to be a thing whether we like it or not, because it is useful. The only question really is whether UI automation for various app platforms is going to be unified or fragmented. The success and longevity of Appium is testament to the power of unification vs fragmentation. The follow-on question is which standard should be the basis for that unification. What better candidate than the standard pioneered by the most truly open platform of all---the web?

There will of course always be web/browser-specific aspects of W3C standards that may not apply to other platforms (like mobile native app platforms). So far, it's been easy enough to simply ignore or slightly update the semantics of such aspects. But I would caution heavily against an approach which would key the protocol too tightly to the specifics of a given web technology (JavaScript). By the same token I would appreciate if the BiDi spec (which admittedly I have not looked at myself in great detail yet) had the same eye to extensibility as the WebDriver spec (allowing e.g. new types of locator strategies).

I'm happy to work more closely with this group to provide a voice from an external "downstream" ecosystem, if that would be at all useful.

**Comment by jimevans** [comment]
@sadym-chromium I've added a `waitTimeout` parameter to the command parameters. Would that suffice for your purposes for `brosingContext.waitElement`?

@whimboo I believe adding such a parameter to this command would allow the "implicit wait" to be implemented client-side, and make the capability obsolete in the BiDi case.

**Comment by pipobscure** [comment]
> If we move everything to be within `script.callFunction` we are running the risk of having to effectively moving all of the Selenium code into preloaded scripts.

Sorry for butting in late. I'm just starting to get myself acquainted with WebDriver/BiDi and wanted to drop a quick note as I'm seeing a trend.

As you rightly noted above doing everything in `script.callFunction` or `script.evaluate` could present problems. One problem is that this leaves us without the ability to test for scenarios where script execution is not permitted for some reason. (The reasons vary and include *I'm testing smooth degradation of capabilities and have JS turned off* and *This is a secure application that has everything frozen* etc.)

So I'd like to encourage - for the purpose of designing WebDriver/BiDi - to always assume that script evaluation is not available. It's great to have it as an option, and there is nothing wrong with `script.evaluate` in principle, but its availability should never be used as an argument against a feature being needed. (Just my €0.02)
