### ISSUE TITLE
NaN cannot be deserialized from primitive protocol value

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#160]
With the current steps to run for values of type `number` there is no possibility to actually deserialize `NaN`:

https://w3c.github.io/webdriver-bidi/#deserialize-primitive-protocol-value

```
1. type is the string "number"
2. Let number_result be StringToNumber(value).
3. If number_result is NaN, return error with error code invalid argument
```

In case of `NaN` the number will always be `NaN` and result in an invalid argument error.

CC'ing @sadym-chromium

**Comment by whimboo** [comment]
Maybe we could simply change it to:

> 3. If number_result is NaN and value is not "NaN", return error with error code invalid argument

**Comment by whimboo** [comment]
Also should we accept `{ type: "number", value: null }` to be deserialized as `0`?

CC @jgraham

**Comment by foolip** [comment]
Handling the NaN case first would be straightforward to understand and avoids trying to parse when we know it will fail.

**Comment by whimboo** [comment]
https://github.com/w3c/webdriver-bidi/pull/161 actually fixed that issue.
