### ISSUE TITLE
Does the specification leak registered event subscriptions?

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#166]
While working on the implementation of `browsingContext.contextCreated` for Firefox and reading `browsingcontext.contextDestroyed` I cannot find anything in the specification that mentions the removal of closed browsing contexts from the [browsing context event map](https://w3c.github.io/webdriver-bidi/#event-browsing-context-event-map). That means that over time subscriptions for specific browsing contexts will remain in this map even when they aren't attached anymore.

Should we add some text to at least mention implementation specific steps to run to clean-up the map?

**Comment by sadym-chromium** [comment]
I guess, as long as the browsing context has a unique ID, it's not an issue, while removing them from the map can potentially be racy with some belated events.

**Comment by whimboo** [comment]
Please note that the map was recently renamed to [navigable event map](https://w3c.github.io/webdriver-bidi/#event-navigable-event-map). Also checking the HTML spec we call into `browsingContext.contextDestroyed` when closing any top-level or child navigable:

https://html.spec.whatwg.org/#destroy-a-top-level-traversable

That means that we are basically fine and should not leak any closed navigable, also because navigables have an id that will not change. I think that we can close this issue.
