### ISSUE TITLE
"url" property for browsingContext.contextCreated is always "about:blank"

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#173]
The current spec defines that the `browsingContext.contextCreated` event's `url` property should be taken from the browsing context's active document once initially set. This means in (nearly) all the cases this will be `about:blank` due to the load of the initial `about:blank`. Due to this behavior it makes the property completely useless.

We seem to have at least two different options here:

1) We could remove the `url` property and just return the browsing context id. That way the event is fired as early as possible and allows the client to further track navigation for that particular browsing context.

2) We could let the `url` property return the target of the navigation, eg. when a script calls `window.open("http://example.com", ...)` it would contain `http://example.com`. This comes with the caveat that we cannot cover a possible redirect. Also the event might be sent out too late and the navigation events from the initial navigation might have been missed.

All this opens the question if we want to support the initial `about:blank` or not (see issue #141).

CC'ing @jgraham, @sadym-chromium, @foolip, @bwalderman.

**Comment by sadym-chromium** [comment]
I'm totally for the option 1.

**Comment by whimboo** [comment]
One note to option 1: 

CDP actually lists the `url` as part of the [`TargetInfo`](https://chromedevtools.github.io/devtools-protocol/tot/Target/#type-TargetInfo) type which maps to the [`BrowsingContextInfo`](https://w3c.github.io/webdriver-bidi/#type-browsingContext-BrowsingContextInfo) type in Webdriver BiDi. Given that `url` is not optional in both protocols (which is fine), we cannot actually remove it. As such we have to return `about:blank`, which clients then have to ignore.

This means we have to agree on using `about:blank` or some potential target URI for an upcoming navigation (which might be hard to get for individual remote implementations).

**Comment by whimboo** [comment]
Actually that's a good point. So it looks like that we reached consensus here and that I don't have to bring it up anymore for tomorrows monthly meeting. I'm going to close this issue.

**Comment by whimboo** [comment]
Lets see https://github.com/web-platform-tests/wpt/pull/34641. The `url` property can still be `about:blank` given that the BiDi spec hooks into https://html.spec.whatwg.org/multipage/browsers.html#creating-a-new-browsing-context after step 19 but not until step 23 when the final page has been loaded. 

@jgraham Would it be ok to change the BiDi spec accordingly to have a consistent `url` property?

**Comment by sadym-chromium** [comment]
@whimboo what do you mean in "consistent property"?
