### ISSUE TITLE
Invalid IDL definition of SandboxWindowProxy

### ISSUE THREAD

**Issue by tidoust** [w3c/webdriver-bidi#179]
The addition of a [basic API surface for sandboxed script execution](https://github.com/w3c/webdriver-bidi/commit/60005be325979d5416c86aab2fd189354c28d980) introduces an invalid IDL definition for `SandboxWindowProxy`:

```webidl
[Exposed=]
interface SandboxWindowProxy : WindowProxy {};
```

`Exposed=` is not a valid construct for the [extended attributes](https://webidl.spec.whatwg.org/#idl-extended-attributes) that are used in web specs, and for [`Exposed`](https://webidl.spec.whatwg.org/#Exposed) in particular. There needs to be a right hand side. `[Exposed=*]` would work if you don't know yet where the interface should be exposed.

I'm also wondering whether inheriting from [`WindowProxy`](https://html.spec.whatwg.org/multipage/window-object.html#windowproxy), which is an [exotic object](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#exotic-object), is doable. Cc @w3c/webidl-design for feedback.

**Comment by jgraham** [comment]
Right, `SandboxWindowProxy` is basically like `WindowProxy` in that it's providing mediated access to an underlying `Window`. The details are basically undefined at the moment (and I think are quite hard to define; the platform doesn't currently provide a convenient way to talk about the underlying IDL object properties seperate from a JS object, even those this is a real distinction in browsers and important to the encapsulation properties that are offered by the sandbox implementations in Gecko/Blink/WebKit).

Anyway, if this being defined as IDL is causing some immediate problems for other tooling we can move the "definition" into prose.

**Comment by tidoust** [comment]
> Anyway, if this being defined as IDL is causing some immediate problems for other tooling we can move the "definition" into prose.

A prose definition would be great :)

The crawler that extracts such IDL constructs indeed chokes on this. The Web IDL parser currently manages to parse the construct but [could soon report a validation error](https://github.com/w3c/webidl2.js/issues/570#issuecomment-1063877457).

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/185

**Comment by foolip** [comment]
Fixed!
