### ISSUE TITLE
Specify how to establish a connection

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#19]
https://github.com/w3c/webdriver/issues/1498 concerns what kinds of messages to exchange over a connection, but to get off the ground we also need to first enumerate possible connections and establish a connection. This would, I think, also be the "upgrade mechanism" for getting from a WebDriver HTTP connection to a BiDi connection.

Straw proposal, assuming an already created WebDriver session:

`GET /session/{session id}/targets` to enumerate targets to which one can connect. Among other information there would be a ([WebSocket?](https://github.com/w3c/webdriver/issues/1498#issuecomment-633679523)) URL to connect to. That's all.

However, this is probably a flawed proposal, and it seems like the choices here will have large consequences. Questions that come to mind:
- What is the scope of a connection, is it a single [realm](https://tc39.es/ecma262/#sec-code-realms), an [agent cluster](https://tc39.es/ecma262/#sec-agent-clusters), a [browsing context group](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-group), the whole browser, or something else?
- Is it a [goal](https://github.com/w3c/webdriver/issues/1499) to reduce the number of connections by multiplexing?
- Should it be possible to create a session using BiDi, not merely "upgrade" one?

**Comment by jgraham** [comment]
Filed https://github.com/w3c/webdriver/pull/1523 to give us hooks to work with in the WebDriver spec.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/24 is an initial cut at this.

**Comment by foolip** [comment]
There are still a bunch of issues, but the basics of this have been specified.
