### ISSUE TITLE
Support for handling user prompts

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#191]
Several commands could spawn user prompts (alert, confirm, prompt) on the current page and we need a way to handle these. There should be support for accepting, dismissing, getting the text and entering text.

Also in WebDriver HTTP there is the `unhandledPromptBehavior` capability that defaults to dismiss and notify.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/195

**Comment by whimboo** [comment]
@jgraham what kind of work is left to do for this issue? Your PR #195 covers quite a lot.

**Comment by thiagowfx** [comment]
+1 - should this be closed? Is anything else missing?

**Comment by whimboo** [comment]
I think that we should close. If there are remaining issues or bugs we can create a separate issue or PR.
