### ISSUE TITLE
Network request logging

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#196]
We should provide a module for network request logging. This is important for a few reasons:
* Direct testing use cases e.g. verifying that a specific request was made after performing some action.
* Performance testing e.g. by allowing clients to directly produce performance timelines or genera of HAR files that can be used to store resource timing information and detect regressions when changes are made.
* As a stepping stone on the way to full network request interception, which is a requirement from clients e.g. Selenium ("interception" will add the possibility to not just observe requests but also to modify them during their lifecycle).

For the initial cut I'm going to assume that only HTTP requests are in-scope, although I'm sure we'll want to extend this to Websockets messages in the future.

Interception is also out of scope for now, but the design should take into account the possibility to modify requests during the lifecycle in the future. HTTP Auth is a special case of that, which I think we could add before full request interception.

There are various pieces of prior art here:
* CDP's [Network module](https://chromedevtools.github.io/devtools-protocol/tot/Network/).
* WebExtension's [WebRequest API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest)
* Gecko's devtools, which seems to be somewhat less well documented(?) although there are some [backend](https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsIHttpProtocolHandler.idl) [interfaces](https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsIHttpActivityObserver.idl) which give a clue to the kind of lifecycle events that exist.

The WebExtensions API seems to be the best documented in terms of the lifecycle. I think the following is a rough correlation between the different lifecycle events here (but this is based on documentation, not experiment, so I will have made some errors; ? indicates something I'm explicitly not sure about):

| WebExtensions Event | CDP Event |
| --- | --- |
| onBeforeRequest | |
| onBeforeSendHeaders | Network.requestWillBeSent |
| onSendHeaders | |
| onHeadersReceived |  | 
| onAuthRequired | Fetch.authRequired |
| onResponseStarted | Network.responseReceived |
| onBeforeRedirect | ? |
| onCompleted | Network.requestServedFromCache or Network.dataReceived / Network.loadingFinished ? |
| onErrorOccurred | Network.loadingFailed |

Also CDP has Fetch.requestPaused which seems to be fired roughly before Network.requestWillBeSent and before Network.loadingFinished (I think).

I wonder how tied we are to the details of the CDP model here in terms of ease of transition. It seems like if we emitted events corresponding to the WebExtensions events then we'd have a richer API and more platform consistency in general. The main difference in terms of where in the lifecycle we have events, seems to be that there's no `dataReceived` event in WebExtensions, which makes it harder to track progress on an ongoing request.

**Comment by jgraham** [comment]
It seems like Puppeteer only depends on `Network.requestWillBeSent`, `Network.loadingFinished`, `Network.loadingFailed` and `Network.requestWillBeSent`, so maybe the `Network.dataReceived` event in particular isn't a requirement for thet use case
https://github.com/puppeteer/puppeteer/blob/e68d6c7f3f4233c48c932344b9356b3f951ec0c0/src/common/NetworkEventManager.ts#L4

**Comment by whimboo** [comment]
@jgraham you duplicated `Network.requestWillBeSent` above. Basically it should be `Network.responseReceived` instead.

Beside these mentioned events there are also [`Network.requestWillBeSentExtraInfo`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSentExtraInfo) and [`Network.responseReceivedExtraInfo`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo)

**Comment by paulirish** [comment]
I recently was taking inventory of all the network request timings and associated instrumentation. This isn't exhaustive but should help capture how the key timings relate to the CDP events

https://raw.githubusercontent.com/GoogleChrome/lighthouse/master/docs/Network-Timings.svg

As a CDP client, it's extra painful to deal with differing units (seconds vs milliseconds) along with the ~timeOrigin being different, depending on what you're looking at. 

-----

> I've been hoping we can get away without *ExtraInfo events.

Me too, my vague understanding is that they were needed due to ~chromium network service running out of process & greater cross-origin isolation. They seem to matter around cross-origin redirects, and collecting raw response headers.. but I don't know more details.

**Comment by christian-bromann** [comment]
@whimboo @jgraham can this be closed?
