### ISSUE TITLE
Unify Date serialization and deserialization

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#202]
Currently:
* [serialization](https://w3c.github.io/webdriver-bidi/#data-types-protocolValue-RemoteValue-serialization) specifies the Date value should be a result of [Date.ToDateString](https://tc39.es/ecma262/#sec-todatestring)([thisTimeValue](https://tc39.es/ecma262/#thistimevalue)(value)), which ends up with a string like `Thu May 05 2000 15:12:53 GMT+0200 (Central European Summer Time)`.
* [deserialization](https://w3c.github.io/webdriver-bidi/#data-types-protocolValue-LocalValue-deserialization) specifies a check if the value matches [Date Time String Format](https://tc39.es/ecma262/#sec-date-time-string-format) "ISO 8601 calendar date extended format", which look like `YYYY-MM-DDTHH:mm:ss.sssZ`.

I suggest to make serialized Date value to be "ISO 8601 calendar date extended format".

**Comment by lutien** [comment]
Hey @sadym-chromium, could I work on this issue?
I'm working on the implementation part of the serialization now, so would be great to fix the issue before.

**Comment by whimboo** [comment]
@sadym-chromium I've asked @lutien to work on this issue. I hope you don't mind. :)

**Comment by sadym-chromium** [comment]
There is one question regarding TimeZone: https://github.com/w3c/webdriver-bidi/pull/237#discussion_r903498978

**Comment by whimboo** [comment]
> There is one question regarding TimeZone: [#237 (comment)](https://github.com/w3c/webdriver-bidi/pull/237#discussion_r903498978)

This question has been solved.
