### ISSUE TITLE
Add command for printing to PDF 

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#210]
Users want to print pages as PDF and using WebDriver classic isn't ideal when this should run in parallel.

I assume it's a command that we also want to get added to the `browsingContext` module.

CC'ing @jgraham.

**Comment by whimboo** [comment]
The Chrome DevTools protocol has the command as [`Page.printToPDF`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF). So a command named like `browsingContext.printToPDF` may make sense for BiDi.

**Comment by whimboo** [comment]
I've discussed with @jgraham and he proposed `browsingContext.print`. The benefit here is that we could re-use the same command for other output formats as well.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/363

**Comment by sadym-chromium** [comment]
Can the task be closed as implemented in #363?
