### ISSUE TITLE
What types of events are going to be able to be listened to for webdriver Bidi?

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/webdriver-bidi#211]
I was checking out the goals for webdriver bidi and I was wondering if the "DOM Events" that are going to be listened to are the same as the DOM events found on this link: https://www.w3schools.com/jsref/dom_obj_event.asp.

**Comment by jgraham** [comment]
This again seems like a question. Script execution will allow a client to listen to any DOM event. There will also be additional events from the protocol itself.
