### ISSUE TITLE
Would access to Devtools mean that we could be able to force the element state of an element to change?

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/webdriver-bidi#212]
I was wondering if the goal of "Access to native devtools protocol" would allow users to use the force element state function.

Also, I was wondering if it could be explained how the browser is able to force the element state to change and if it were possible to do it in Selenium without webdriver Bidi.

**Comment by jgraham** [comment]
Sorry, I don't really understand what feature is being requested here. In general it's OK to document use cases that you'd like to solve with BiDi as spec issues, but it's not really appropriate as a forum for asking questions.
