### ISSUE TITLE
Improve CDDL implementation checks to avoid further mistakes

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#223]
As seen in issue #218 there is a failure in our CDDL definition for `CapabilitiesRequest`. Sadly this is not detected by our Rust CDDL implementation task in the GitHub CI.

As suggested by @jgraham via https://github.com/w3c/webdriver-bidi/pull/222#pullrequestreview-997850966 we may want to add some example messages to verify that parsing AND validation actually works.

CC @jgraham and @sadym-chromium

**Comment by whimboo** [comment]
See also issue #272 where certain commands are missing in the `CommandData` definition.

**Comment by sadym-chromium** [comment]
As discussed offline in Berlin, we need not only a validation step, but generating types based on the CDDL as well.

**Comment by whimboo** [comment]
I've a PR for issue #275 now - this tracks the broken generation of remote vs. local cddl files given a missing support for multiple cddl names within a single `pre` node.

**Comment by whimboo** [comment]
With the 0.9.0 release of cddl the validation capabilities of the tool have been improved drastically and a lot of broken definitions are visible (see issue #297). With these improvements I don't think that we will have to do anything else on our side for now.

I'll attach a PR that will fix it.

**Comment by whimboo** [comment]
Fixed by PR #298.
