### ISSUE TITLE
Serialize as remote value misses to pass "child ownership" to "serialize as a list"

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#227]
Within [`serialization as remote value`](https://w3c.github.io/webdriver-bidi/#data-types-protocolValue-RemoteValue-serialization) the steps `4.1` for serializing an array calls [`serialize as a list`](https://w3c.github.io/webdriver-bidi/#serialize-as-a-list) but doesn't pass the `child ownership` argument which is required by that algorithm after `maxDepth`:

> Let serialized be the result of [serialize as a list](https://w3c.github.io/webdriver-bidi/#serialize-as-a-list) given [CreateArrayIterator](https://tc39.es/ecma262/#sec-createarrayiterator)(value, value), max depth, serialization internal map and realm.

**Comment by whimboo** [comment]
CC @sadym-chromium

**Comment by sadym-chromium** [comment]
I'm OOO till the next week

**Comment by whimboo** [comment]
Fixed by #228.
