### ISSUE TITLE
"browsingContext.captureScreenshot" should support element screenshots

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#229]
WebDriver has a command to take a screenshot just of the bounding rect of a specific element. We should have the same command in WebDriver, or extend the context screenshot command with the option to take an element sharedId to specify the bounding client rect.

**Comment by jrandolf** [comment]
I think the only reason we would want element-based clips is if we supported full capture of the element, even if it's beyond the viewport. Based on the current spec, we scrollIntoView the element, so its likely this is not the intention so I don't see why it's necessary when it can be done client side.

**Comment by jgraham** [comment]
This is now supported.
