### ISSUE TITLE
Missing `child ownership` argument when serializing the key in `serialize as a mapping`

### ISSUE THREAD

**Issue by lutien** [w3c/webdriver-bidi#233]
It looks like in [serialize as a mapping](https://w3c.github.io/webdriver-bidi/#serialize-as-a-mapping) point 2.6 when we want to serialize a child key as a remote value `child ownership` argument should be also present to align with serialization of the value

**Comment by whimboo** [comment]
This is a bug in the spec and similar to issue #227. A fix would be welcome.
