### ISSUE TITLE
Consider making Element serialize differently from other Node types.

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#235]
Some commands really want an Element type (e.g. to use as a pointer origin) and not e.g. a Document or Attribute. So it might make sense to make Element nodes have a different type to general DOM nodes in the serialization instead of having a single node type.

**Comment by sadym-chromium** [comment]
AFAIK, `nodeType==1` points to the node being an element. Is the suggested change intended to tell apart the node and element even after serialization with `MAX_DEPTH=0`?

**Comment by jgraham** [comment]
Given that we have a very generic RemoteValue type, this probably doesn't make sense; we just need to do runtime checks to validate that we got the correct type of value. As you say it's still possible to tell the difference between an Element and another kind of Node; you just look at the properties. But it doesn't show us as part of the type name.

**Comment by whimboo** [comment]
Additionally to the comment from @jgraham I can say, while working on Element serialization in Firefox, that we also need to share elements with WebDriver classic and we definitely don't want to have all node types cached as well in a storage that for WebDriver classic should only contain elements.

Given that for WebDriver classic we have caches for Element and Shadow Roots separated we might even think about having three distinct types?

**Comment by sadym-chromium** [comment]
SGTM

**Comment by whimboo** [comment]
@jgraham should this be a topic for the W3C meeting next week or doesn't it need any further discussion?

**Comment by whimboo** [comment]
As [discussed during today's W3C meeting](https://www.w3.org/2022/12/01-webdriver-minutes.html#t03) we are not going forward with this proposal. As such closing.
