### ISSUE TITLE
StatusResult should be SessionStatusResult

### ISSUE THREAD

**Issue by zcorpan** [w3c/webdriver-bidi#240]
The names here don't match:

```
SessionResult = (StatusResult)
```
https://w3c.github.io/webdriver-bidi/#module-session-definition

```
SessionStatusResult = {
  ready: bool,
  message: text,
}
```
https://w3c.github.io/webdriver-bidi/#command-session-status

**Comment by zcorpan** [comment]
Also I guess it should list out all of the session commands' return types?

```
SessionResult = (SessionStatusResult // SessionNewResult // EmptyResult)
```

**Comment by thiagowfx** [comment]
This seems to have been fixed in the meantime (the first comment). Can we close this issue?

**Comment by whimboo** [comment]
What we still need is to get the `session.NewResult` added. `EmptyResult` is not needed given that this is already covered in `ResultData`. I'll create a separate PR for that so that we can close this issue.
