### ISSUE TITLE
Question about script evaluate/callFunction and strict mode

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#251]
It's not clear to me how evaluate & callFunction should decide to run in strict or non-strict mode.

Based on https://tc39.es/ecma262/#sec-strict-mode-code I feel like we fall under: 
> Eval code is strict mode code if it begins with a [Directive Prologue](https://tc39.es/ecma262/#directive-prologue) that contains a [Use Strict Directive](https://tc39.es/ecma262/#use-strict-directive) or if the call to eval is a [direct eval](https://tc39.es/ecma262/#sec-function-calls-runtime-semantics-evaluation) that is contained in strict mode code.

Which can work for script evaluate, we can easily add a `"use strict";` at the beginning. But it is more complicated for callFunction, because adding a `"use strict";` before wrapping the `functionDeclaration` in parenthesis will result in invalid code.

Is strict mode supposed to be selected/infered from somewhere else? Or do we need to make it an explicit option?

**Comment by juliandescottes** [comment]
cc @jgraham

**Comment by sadym-chromium** [comment]
Users can use the structure like `script.callFunction` with `"functionDeclaration": "()=>{'use strict';x=1}"`

**Comment by juliandescottes** [comment]
Good point. Not sure if I missed that it was possible to declare that in the function declaration or if I had something else in mind, but I guess it's fine to say that this is up to the user. There's probably no strong reason to enforce one or the other on our end. 

I think it's fine to close this now.

**Comment by sadym-chromium** [comment]
Let me add WPT tests for that first

**Comment by sadym-chromium** [comment]
https://github.com/web-platform-tests/wpt/pull/35448

**Comment by sadym-chromium** [comment]
> Let me add WPT tests for that first

Oh, WPT tests are not related to the spec. Closing.
