### ISSUE TITLE
Is an empty string a valid sandbox name?

### ISSUE THREAD

**Issue by lutien** [w3c/webdriver-bidi#258]
The specification only says [that sandbox name should be a string](https://w3c.github.io/webdriver-bidi/#sandbox), but doesn't disallow it to be an empty string. But the topic of if it actually should be allowed came up multiple times during the review of the sandbox feature.
See:
- https://github.com/web-platform-tests/wpt/pull/35465#pullrequestreview-1075198119
- https://phabricator.services.mozilla.com/D153440#inline-847815

**Comment by sadym-chromium** [comment]
Let's consider introducing the new entity "default sandbox", which is not a sandbox per se, but rather the context's default realm. In such a case, we can define an empty string to point the "default sandbox".

**Comment by whimboo** [comment]
PR #300 was merged with the result that an empty sandbox name is considered the default realm.

**Comment by whimboo** [comment]
@sadym-chromium can you please update the wdspec tests and add new ones to handle this specific scenario?

**Comment by whimboo** [comment]
Actually there is PR #304 which is still open.

**Comment by sadym-chromium** [comment]
The described behaviour is defined in https://github.com/w3c/webdriver-bidi/pull/304.
