### ISSUE TITLE
RealmType is not defined

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#268]
At https://w3c.github.io/webdriver-bidi/#command-script-getRealms, `GetRealmsParameter` is defined as

```
GetRealmsParameters = {
  ?context: BrowsingContext,
  ?type: RealmType,
}
```

But `RealmType` is not defined anywhere. 

I imagine it's a text that can take any of the `type` values listed in the various RealmInfo types https://w3c.github.io/webdriver-bidi/#type-script-RealmInfo? Meaning
- audio-worklet
- dedicated-worker
- paint-worklet
- service-worker
- shared-worker
- window
- worker
- worklet

Should we either explicitely define it or just update `GetRealmsParameters` to use `?type: text`?

**Comment by whimboo** [comment]
Closing because #269 has been merged.
