### ISSUE TITLE
Inconsistent generation of local and remote CDDL files (missing definitions)

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#275]
When generating the remote.cddl file I miss references to `CapabilitiesRequest` even through [this type is marked for both local and remote](https://w3c.github.io/webdriver-bidi/#type-session-capabilitiesRequest).

```
CapabilitiesRequestParameters = {
  ?alwaysMatch: CapabilitiesRequest,
  ?firstMatch: [*CapabilitiesRequest]
}
```

Instead it's only listed in `local.cddl`, which isn't actually needed there given that the client won't have to parse that anyway.

**Comment by muccimoz** [comment]
2-points for reference.
