### ISSUE TITLE
Switch to ubuntu-20.04 environment in test.yml

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#277]
Checking GitHub actions runs will give the following annotation:

https://github.com/w3c/webdriver-bidi/actions/runs/3018269615

> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

As such we should switch the environment.

**Comment by muccimoz** [comment]
1-point for reference.
