### ISSUE TITLE
Add support for setting, getting, and deleting cookies

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#287]

**Comment by whimboo** [comment]
Given that we haven't had an issue for deleting cookies yet and that it actually fits into this issue I've updated the summary of the issue to reflect that as well.

**Comment by whimboo** [comment]
See as well some ongoing discussions on https://github.com/w3c/webdriver-bidi/pull/423.

**Comment by lolaodelola** [comment]
Hi folks, my colleague @jugglinmike  and I have been thinking about ways we could implement Cookies (get, set & delete) and have come up with three possible solutions and would love to hear what folks think.

1. We specify every way that a browser does cookies and include this in the API. So getCookie("foo", container: containerName) would get the named foo from the Firefox container named bar, and getCookie("foo", requestSourceOrigin: [example.com](http://example.com/)) would get the named cookie from the request source origin, etc.

2. We specify a mechanism to include generic properties for your requests. getCookie("foo", source: container | requestSourceOrigin) So you can add whatever you want and implementers can define what those things are and what the browser does in response. This method would mean we don’t have to get into the details of the request, source origin, etc & allow the browsers to interpret as they will.

3. We specify that when getCookie("foo") returns any and everything, for every request source origin, every container. "get" could return an array (which could be empty in some instances), while "set" could create a cookie that applied to all contexts, and "delete" would remove the named cookie in any & all contexts where it was defined.

There are pros and cons to each of these methods, so none is perfect, and I’m not particularly attached to any, so it’d be great to hear what others think.
cc: @mathiasbynens

**Comment by OrKoN** [comment]
@jgraham and I were discussing cookies right now on the webdriver channel. It looks like the option 3 would be preferable and in line with the discussion there but we need to include the cookie key into the matching cookies and probably add a way to compute a cookie key for a given context.

**Comment by jgraham** [comment]
So the problem is forwards compatibility.

Let's say we adopt a design where you have browser-specific partition keys, and any key the client is missing is interpreted as a wildcard.

For getting cookies that's not totally terrible, but there are still sharp edges. For example if initially cookies are only keyed on destination origin (the default), then `getCookies("name", host="example.org")` is going to always just return one cookie. But if it then adds partitioning by source origin, there may well be more than one cookie returned, and that would almost certainly lead to unexpected results in automated tests, even though the site under test would in fact be working correctly.

For setting it may well not work at all. The issue is that you can't know the values that different key parts might have in the future. So if I `setCookie("name", "value", host="example.org")` in a browser with only destination-keyed cookies, it will naturally work when `example.com` tries to send data to `example.org`. But if a later version of that browser adds source origin keyed cookies, then at the time I set the cookie the browser doesn't know that it will later be asked to make a request from `example.com`, so it doesn't know to insert the cookie with that key. So you either need to allow wildcard keys in the underlying cookie store which it isn't obvious that you should (given the entire point is state partitioning), or you somehow need to set the cookie just in time whenever something happens that would correspond to a new key. I can check in detail what Firefox does, but I'd be surprised if we could support this.

**Comment by OrKoN** [comment]
I imagined something like this:

```
type Cookie {
   name: string;
   value: string;  
   host: string;
   ....
   partitionKey: string|undefined; // used for partitioning, clients have no insights into the structure of the key.
}

getCookies(): Cookies[]; // a way to get all cookies stored in the browser; 
// perhaps with filter by name/key/etc.

addCookie(cookies: Cookie[]); // adds cookies to the storage; 
 // UnsupportedOperation if the partition key is wrong; loosing future compatibility I guess if browsingContext.getCookiePartitionKey is not used? 
 // but I don't see a way if browsers can make breaking changes here.

removeCookie(cookies: Cookie[]); // perhaps only a subset of data is needed for removal?

browsingContext.getCookiePartitionKey(): string // returns a cookie key for the context
```

This would not support the wildcards (should we? based on James' comments I am not sure we can/should). It should cover the potential triple keying by the container/profile in the sense that the bidi implementations would need to rewrite the partition keys using the browser-specific algorithms so the clients would get some partitionKey token that does not match 1 to 1 to what is actually in the storage.

**Comment by jgraham** [comment]
Yeah, so that design is more or less the best idea I have as well. But it doesn't work if you want to be able to set a cookie before the _first_ request to a site. If the partition keys are fixed between sessions people will absolutely try to get around that by hardcoding known keys in their tests (which will then break again when the browser version changes). On the other hand, I guess browsers must have a way of dealing with cookies set in older versions after updates, so maybe they already have to do something sensible for missing fields. But that might work better for user-scenarios (where no one is directly inspecting the cookies, and they can just depend on the server to set any missing cookies) compared to tests scenarios where direct inspection is the point.

**Comment by jugglinmike** [comment]
We've just started iterating on specification text in gh-501, but we've already made some assumptions for which I haven't yet found justification in the WebDriver BiDi project's public records. I'm seeking confirmation in this thread because these details will fundamental to any solution--not just the one we're currently working on.

- Cookie retrieval
  - Should we specify `getCookie` (i.e. "get the named cookie"), `getCookies` (i.e. "get any number of named cookies"), `getAllCookies` (i.e. "get all the cookies"), or some combination?
  - Precedence
    platform                        | get the named cookie | get any number of named cookies | get all the cookies
    --------------------------------|----------------------|---------------------------------|--------------------
    [DOM][DOM]                      | :x:                  | :x:                             | :heavy_check_mark:
    [WebDriver Classic][WebDriver]  | :heavy_check_mark:   | :x:                             | :heavy_check_mark:
    [Chrome Devtools Protocol][CDP] | :x:                  | :x:                             | :heavy_check_mark:
  - Assumptions
    - `getAllCookies` is meaningfully more powerful because it allows developers to discover cookies (one potential use case: writing a test which fails in the presence of any unexpected cookie).
    - `getCookie` and `getCookies` are superfluous in the presence of `getAllCookies` (the waste of transmitting unneeded data is negligible, and library authors can build `getCookie` and `getCookies` on top of it)
- Cookie modification
  - Should we specify `setCookie` (i.e. "modify one cookie") or `setCookies` (i.e. "modify any number of cookies")?
  - Precedence
    platform                        | modify one cookie  |  modify any number of cookies
    --------------------------------|--------------------|------------------------------
    [DOM][DOM]                      | :x:                | :heavy_check_mark:
    [WebDriver Classic][WebDriver]  | :heavy_check_mark: | :x:
    [Chrome Devtools Protocol][CDP] | :x:                | :heavy_check_mark:
  - Assumptions
    - `setCookies` is more versatile since it allows developers to set a single cookie
    - `setCookie` is superfluous in the presence of `setCookies` (the syntax overhead on developers will be minor)
- Cookie deletion
  - Should we specify `deleteCookie` (i.e. "delete the named cookie"), `deleteCookies` (i.e. "delete any number of named cookies"), `deleteAllCookies` (i.e. "delete all the cookies"), or some combination?
  - Precedence
    platform                        | delete the named cookie | delete any number of named cookies | delete all the cookies
    --------------------------------|-------------------------|------------------------------------|-----------------------
    [DOM][DOM]                      | :x:                     | :heavy_check_mark:                 | :x:
    [WebDriver Classic][WebDriver]  | :heavy_check_mark:      | :x:                                | :heavy_check_mark:
    [Chrome Devtools Protocol][CDP] | :x:                     | :x:                                | :heavy_check_mark:
  - Assumptions
    - `deleteCookie` and `deleteCookies` are superfluous in the presence of `setCookie` or `setCookies`
    - `deleteAllCookies` is superfluous in the presence of `getCookies` and either "set" API ("get all cookies" followed by "modify any number of cookies" is an acceptable approximation despite being non-atomic)

[DOM]: https://html.spec.whatwg.org/multipage/dom.html#dom-document-cookie
[WebDriver]: https://w3c.github.io/webdriver/
[CDP]: https://chromedevtools.github.io/devtools-protocol/tot/Storage/

**Comment by OrKoN** [comment]
I would be in favour of starting with get(all)Cookies and set(all)Cookies with setCookies(cookies=[]) supporting the deletion use case. @jgraham @sadym-chromium  what's your opinion?

**Comment by sadym-chromium** [comment]
`getAllCookies` SGTM.
WRT `setCookies(cookies: Cookie[])`, I would expect it to append the `cookies` to the list of currently set cookies. Having that, I'd be in favour of having `addCookies(cookies: Cookie[])`, `deleteCookies(cookieNames: String[])` and `deleteAllCookies()` to provide atomicity.

**Comment by OrKoN** [comment]
After a discussion offline, I am with Maksim and James that setCookies should not delete.

**Comment by jugglinmike** [comment]
> `deleteAllCookies()` to provide atomicity.

@sadym-chromium Since everything that occurs in this protocol is asynchronous, I'm having trouble coming up with a situation where atomicity is meaningful. A command like `storage.deleteAllCookies` could induce a browser to clear its cookie store, but because every BiDi client invariably needs to wait for a subsequent WebSocket message, it seems like they still won't be able to guarantee that the store is empty. Can you help me understand how atomicity is important in this context?

> I'd also expect `setCookies` to modify/append but not delete

> After a discussion offline, I am with Maksim and James that setCookies should not delete.

@jgraham @OrKoN It's my understanding that changing an existing cookie's expiry-time to a date in the past is functionally equivalent to deleting that cookie. From [RFC6265](https://httpwg.org/specs/rfc6265.html#storage-model):

> The user agent MUST evict all expired cookies from the cookie store if, at any time, an expired cookie exists in the cookie store.

From my perspective, the decision is not whether "set cookie" should allow deletion, but rather whether BiDi needs a dedicated "delete cookie" command given that "set cookie" will inherently allow deletion. I suppose we could design BiDi's "set cookie" command to be incapable of deletion (e.g. by ignoring the `expires` field of `network.Cookie` or perhaps failing in its presence), though since this kind of conflicts with the existing design of BiDi's types (and also precludes non-deletion usage of that field), I feel I should verify: is that what you folks have in mind?

**Comment by OrKoN** [comment]
@jugglinmike what I meant is that if there are the following cookies in the storage (I guess identified by name + partition keys): (cookie1, cookie2) then calling `setCookies(cookies: [cookie3])` should not remove cookie1 and cookie2 from storage. I believe if you call setCookies(cookies: [cookie2]) with an expiration date that leads to its deletion, I think that would be expected. I would probably expect that you can still add an expired cookie to test that the user agent actually deletes it (e.g., in a WPT test).

**Comment by jgraham** [comment]
> whether BiDi needs a dedicated "delete cookie" command given that "set cookie" will inherently allow deletion.

Yes. Although it's possible to use setCookie to update a cookie so that it's already expired, I don't think we should expect end users to use this rather roundabout method to perform the simple operation of removing a cookie from the cookie jar. I also think that having a dedicated command will make it easier to understand logs and so on, since the intent of the command will be explicit and obvious.

**Comment by jugglinmike** [comment]
Thank you both!

**Comment by gsnedders** [comment]
So, AIUI, there's roughly three cookie models currently in use (sorry, existing discussion here is split between here and PR comments, but let's capture this all in the issue):

 * Firefox (always? or maybe still has a denylist of sites where this doesn't apply?) partitions cookies by first-party, third-party
 * Chrome by default provides unpartitioned cookies to both first and third parties, and allows cookies to opt-in to partitioning via CHIPS (similarly first-party, third-party), with the end-goal of stopping sending cookies to third-parties if they don't opt-in
 * Safari by default provides cookies to only first parties, and allows third-party sites to opt-in to unpartitioned cookie access via `Document#requestStorageAccess` (which requires user interaction)

There's potentially other layers of partitioning, but these are more akin to different top-level cookie stores (essentially what Infra calls a "user agent"). An obvious example is private browsing (in all browsers), but also "containers" in Firefox, "profiles" in Safari, etc. These are really different types of partitioning, as these are linked to UI features to segment storage domains.

**Comment by jgraham** [comment]
@gsnedders I think the design in https://github.com/w3c/webdriver-bidi/pull/501#issuecomment-1725180497 allows for all those scenarios? It is basically up to the implementation to decide which parts of the key it wants to use for a specific request (or reject the request if it doesn't have a complete key). In Safari that might depend on which permissions have already been granted.

**Comment by whimboo** [comment]
This is done via PR #501.
