### ISSUE TITLE
Allow creating new browsing profiles/contexts (similar to Incognito mode)

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#289]
Puppeteer currently allows creating incognito contexts via https://pptr.dev/api/puppeteer.browser.createincognitobrowsercontext. It works similarly to the incognito profile with the distinction that multiple profiles can be created via automation.  

The use cases:

1) The functionality is useful to isolate multiple automation tasks and run them concurrently with low overhead.
2) Ability to configure proxy server settings per profile.  

It has the following properties in Chrome:

1. The created profile has no visible windows/tabs and the window is created when the user explicitly creates a new page (that results in a new window).
2. The profile data is not saved to disk. (Not a requirement for the spec, rather an implementation detail)
3. The profile has storage isolated from other profiles. 
4. The can have its own proxy server configuration and a proxy server by pass list. 
5. Browsing contexts are associated with a profile or belong to the default profile.
6. Profile can be closed by a single command resulting in all pages belonging to it being closed. 

<img width="1225" alt="Screenshot 2022-09-19 at 11 19 31" src="https://user-images.githubusercontent.com/399150/190987168-036f98bb-8dc1-41c4-9c9a-9e6df3891adb.png">

**Comment by OrKoN** [comment]
This Puppeteer API is powered by CDP's Target.createBrowserContext https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext

**Comment by whimboo** [comment]
@OrKoN I assume this feature request is similar to the [`container` feature in Firefox](https://support.mozilla.org/en-US/kb/containers? If yes we might want to get rid of the `profile` part in the issue summary because that's causing irritation with the browser profiles.

**Comment by OrKoN** [comment]
@whimboo @jgraham I have collected the properties for the profiles (called BrowserContext in Puppeteer/CDP) that Puppeteer currently relies on.

**Comment by whimboo** [comment]
@OrKoN where have you noted down those properties? Maybe I miss an update somewhere? Thanks.

**Comment by OrKoN** [comment]
@whimboo in the issue description

**Comment by jgraham** [comment]
Out of those properties the one that worries me is the requirement that no data is written to disk. Why is that a necessary property for clients? (_maybe_ for firefox, some combination of containers and private browsing produces that property, but it seems less obviously observable to automation tools than the other properties, and arguably like an orthogonal concern)

**Comment by whimboo** [comment]
In Firefox we support that very rudimentary for CDP via the container feature at the moment. The related code can be found at: https://searchfox.org/mozilla-central/rev/d81e60336d9f498ad3985491dc17c2b77969ade4/remote/cdp/domains/parent/Target.sys.mjs#41-66

**Comment by gsnedders** [comment]
c.f. https://matrixlogs.bakkot.com/WHATWG/2023-09-15#L4 for terminology discussion here
