### ISSUE TITLE
browsingContext.reload and script.disown commands have no return type

### ISSUE THREAD

**Issue by jimevans** [w3c/webdriver-bidi#293]
While recognizing there is an open issue on what to do when closing the last open top-level browsing context, the [browsingContext.close](https://w3c.github.io/webdriver-bidi/#command-browsingContext-close) command does not specify a return type. Unless there is some language in the spec I'm overlooking which says something like, "return `EmptyResult` if there is no other result type defined," this command (as all commands) should define a return type.

**Comment by sadym-chromium** [comment]
The same problem is with `script.disown`

**Comment by jimevans** [comment]
`browsingContext.close` appears to have been corrected. However, `browsingContext.reload` now has no return type. Changing the title to reflect the current state of the spec.

**Comment by whimboo** [comment]
@sadym-chromium you are still assigned to this issue. Are you going to provide a PR for it?

**Comment by sadym-chromium** [comment]
https://github.com/w3c/webdriver-bidi/pull/382

**Comment by whimboo** [comment]
Thanks! PR #382 got merged.
