### ISSUE TITLE
browsingContext.userPromptClosed event needs result data clarification

### ISSUE THREAD

**Issue by jimevans** [w3c/webdriver-bidi#294]
The [browsingContext.userPromptClosed](https://w3c.github.io/webdriver-bidi/#event-browsingContext-userPromptClosed) event defines a `UserPromptResult` but references `UserPromptInfo` instead. The `params` event data should probably reference `UserPromptResult`. Additionally, to maintain consistency, the `UserPromptResult` structure should probably be named `UserPromptResultInfo`.

**Comment by whimboo** [comment]
This is clearly a bug in the BiDi spec. We most likely want to have `UserPromptOpenedInfo` and `UserPromptClosedInfo` to stay in sync with other events.

Also the `BrowsingContextUserPromptOpened` and `BrowsingContextUserPromptClosed` events miss the `Event` suffix.
