### ISSUE TITLE
Consider differentiate element ID and shared ID

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#330]
Consider providing different element IDs in BiDi and Classic, and add a gateway method translating from one to another.

Instead of sharing the same element ID in Classic and BiDi, consider allowing them to be different with additional BiDi methods 
* `script.getClassicElementIdsByBidiSharedIds([sharedId])`;
* `script.getBidiSharedIdsByClassicElementIds([elementId])`.

Classic and BiDi serialisations are different. Classic serialisation relies on full-depth JSON serialization with some magical object's properties like **"element-6066-11e4-a52e-4f735466cecf"**. In the meantime BiDi has the proper typed serialization with the limited depth. From the implementation perspective, need in always sharing element ids between BiDi and Classic requires some non-trivial logic, and (in Chrome implementation) exposes the BiDi details to the page realm (where Classic object cache lives).

It is required to provide a way for users to share ids between BiDi and Classic. In the same time, not all of the clients need it (BiDi-only clients like Puppeteer would prefer non-observability instead). Having this 2 additional methods allows us to keep the Classic-BiDi compatibility, but draws a line and share the details only for those users who need it.

**Comment by sadym-chromium** [comment]
In Chrome, Classic keeps the map of elements in the document, and implement serialization in the page realm, while BiDi serialization is happening in the backend. If we want in BiDi to use ID returned from Classic, it's not an issue, as we can get it from the document. But if we want to use BiDi element ID in Classic, we have to keep track of all the returned elements, and put them into the document map, which makes the BiDi observable.

**Comment by jgraham** [comment]
> Classic and BiDi serialisations are different. Classic serialisation relies on full-depth JSON serialization with some magical object's properties like "element-6066-11e4-a52e-4f735466cecf"

Note that it's only the actual element id that's shared, so the difference between the container formats isn't very relevant.

**Comment by juliandescottes** [comment]
> BiDi-only clients like Puppeteer would prefer non-observability instead

The shared ids would still only be observable from the same session, right? It's not as if a new classic session would be able to observe the elements used by BiDi?

**Comment by jgraham** [comment]
I think my main question is whether you could just do this automatically during (de)serialization. If you can tell the difference between a classic id and a BiDi is, then each protocol could notice that it has the "wrong" kind of id and insert the id conversion call itself, rather than relying on the user to do it.

Given that offering an upgrade path for large deployed WebDriver testsuites is one of the value propositions of BiDi, forcing clients to do the id conversion themselves seems like a poor choice, if we can avoid it.

**Comment by whimboo** [comment]
I had a look how in how element sharing would work for our implementation in Firefox. And it works pretty well in both directions. Here a webdriver test that demonstrates that:

```
@pytest.mark.asyncio
async def test_shared_elements(bidi_session, current_session, inline, top_context):
    url = inline("<div id='foo'><div id='bar'>")
    await bidi_session.browsing_context.navigate(
        context=top_context['context'], url=url, wait="complete"
    )

    # Classic: Get a reference to 'foo'
    div1 = current_session.find.css("#foo", all=False)
    assert div1.property("id") == "foo"

    # BiDi: Get the references to 'foo' which classic already created and for its child 'bar'
    result = await bidi_session.script.evaluate(
        expression="document.getElementById('foo')",
        target=ContextTarget(top_context["context"]),
        await_promise=False,
    )

    # The shared id from BiDi has to equal the element id from classic
    assert result["sharedId"] == div1.id

    # Classic: Get a reference from 'bar' which BiDi already created
    div2 = current_session.find.css("#bar", all=False)
    assert div2.property("id") == "bar"

    # The shared id from classic has to equal the element id from BiDi
    assert div2.id == result["value"]["children"][0]["sharedId"]
```

The except from the logs:

```
RemoteAgent	TRACE	WebDriverBiDiConnection b7145d5e-c192-411d-ba7a-dcdfb062ad7c -> {"id":2,"method":"browsingContext.navigate","params":{"context":"efad85c1-0e30-491d-8622-922c18702165","url":"http://web-platform.test:8000/webdriver/tests/support/inline.py?doc=%3C%21doctype+html%3E%0A%3Cmeta+charset%3DUTF-8%3E%0A%3Cdiv+id%3D%27foo%27%3E%3Cdiv+id%3D%27bar%27%3E&mime=text%2Fhtml&charset=UTF-8","wait":"complete"}}
RemoteAgent	TRACE	WebDriverBiDiConnection b7145d5e-c192-411d-ba7a-dcdfb062ad7c <- {"id":2,"result":{"navigation":null,"url":"http://web-platform.test:8000/webdriver/tests/support/inline.py?doc=%3C%21doctype+html%3E%0A%3Cmeta+charset%3DUTF-8%3E%0A%3Cdiv+id%3D%27foo%27%3E%3Cdiv+id%3D%27bar%27%3E&mime=text%2Fhtml&charset=UTF-8"}}
webdriver::server	DEBUG	-> POST /session/ed20e8b6-3555-4e4e-99d4-98fff7ec7db7/element {"using": "css selector", "value": "#foo"}
webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"9037e868-2e38-4361-9dc0-1e76cadb1101"}}
webdriver::server	DEBUG	-> GET /session/ed20e8b6-3555-4e4e-99d4-98fff7ec7db7/element/9037e868-2e38-4361-9dc0-1e76cadb1101/property/id
webdriver::server	DEBUG	<- 200 OK {"value":"foo"}
RemoteAgent	TRACE	WebDriverBiDiConnection b7145d5e-c192-411d-ba7a-dcdfb062ad7c -> {"id":3,"method":"script.evaluate","params":{"expression":"document.getElementById('foo')","target":{"context":"efad85c1-0e30-491d-8622-922c18702165"},"awaitPromise":false}}
RemoteAgent	TRACE	WebDriverBiDiConnection b7145d5e-c192-411d-ba7a-dcdfb062ad7c <- {"id":3,"result":{"realm":"7ca13cfe-00a0-4381-b612-56d1422e64c1","result":{"type":"node","value":{"nodeType":1,"localName":"div","namespaceURI":"http://www.w3.org/1999/xhtml","children":[{"type":"node","value":{"nodeType":1,"localName":"div","namespaceURI":"http://www.w3.org/1999/xhtml","children":null,"childNodeCount":0,"attributes":{"id":"bar"}},"sharedId":"8eb6c983-c8c6-4be5-8827-aaa88be99405"}],"childNodeCount":1,"attributes":{"id":"foo"}},"sharedId":"9037e868-2e38-4361-9dc0-1e76cadb1101"}}}
webdriver::server	DEBUG	-> POST /session/ed20e8b6-3555-4e4e-99d4-98fff7ec7db7/element {"using": "css selector", "value": "#bar"}
webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"8eb6c983-c8c6-4be5-8827-aaa88be99405"}}
webdriver::server	DEBUG	-> GET /session/ed20e8b6-3555-4e4e-99d4-98fff7ec7db7/element/8eb6c983-c8c6-4be5-8827-aaa88be99405/property/id
webdriver::server	DEBUG	<- 200 OK {"value":"bar"}
```

That means when our classic implementation creates an element reference it can be used with BiDi, and the same happens vice versa. If there is a BiDi only session first that creates references those would not leak into any classic session because no WebDriver classic client would be able to create a new session because classic supports a single session only. Also as long as both classic and BiDi have the same session id sharing will work, if there would be an additional BiDi session then it would indeed have their own cache.

**Comment by jgraham** [comment]
I don't think we want multiple IDs for the same element.

The most obvious solution is that when it comes to serializing elements you have to do the equivalent of `getClassicIdsByBiDiSharedIds` to see if there's already a Classic ID for the elements, and where there is use that (and vice-versa for BiDi ids in classic). I assume you'd optimise that with a cache of already seen ids, but of course it would still add some overhead.

**Comment by whimboo** [comment]
Shouldn't the element id lookup be cheap anyway given that the `sharedId` is a string and the `known elements` in classic are a hash keyed by that string?

**Comment by sadym-chromium** [comment]
The `getClassicElementIdsByBidiSharedIds` and `getBidiSharedIdsByClassicElementIds` are quite expensive operations, especially when done at the output during serialization for each returned element.

**Comment by sadym-chromium** [comment]
ClassicID and the BiDiID are stored in the different way: one in the CDP backend, another in the window.document. And we would prefer to use ClassicID from BiDi only when it is absolutely necessary, meaning when ClassicID is used as an argument for the BiDi command. From the Classic side there are performance limitations as well. As long as the serialization is happening in the realm, there is no way to get BiDi ID form the CDP backend. So output should be parsed and all the element ID translated in BiDi format one by one, which is very expensive.

We are still brainstorming on how duplication can be avoided.

**Comment by sadym-chromium** [comment]
https://github.com/w3c/webdriver/pull/1702 should allow implementing the proper solution on Chromium side.
