### ISSUE TITLE
I noticed a comment that was incorrectly capitalized

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/webdriver-bidi#341]
In the file index.bs, the lines 2401 - 2403 have an incorrect capitalization for an element.

The lines are:
- #### The session.subscribe Command #### {#command-session-subscribe}
- The <dfn export for=commands>session.subscribe</dfn> command enables certain events

The text "session.subscribe" should be "session.Subscribe"

**Comment by whimboo** [comment]
While the CDDP definitions use a capital first letter the underlying WebDriver API still uses a lower-case letter for the command. This is equal to all the commands. So `session.subscribe` is the method name of the BiDi command, and that is what's reflected in the various headings, and not the CDDL name.

If I missunderstood something please let me know.
