### ISSUE TITLE
Important: url dfn needs for attribute

### ISSUE THREAD

**Issue by annevk** [w3c/webdriver-bidi#347]
https://w3c.github.io/webdriver-bidi/#navigation-status-url doesn't have a for attribute, making it compete with the global definition of URL.

Which leads to https://github.com/whatwg/fetch/issues/1580.

Could you please fix this soonish?

**Comment by whimboo** [comment]
A follow-up was pushed for `id` and `status` as well (https://github.com/w3c/webdriver-bidi/pull/349).
