### ISSUE TITLE
Getting

### ISSUE THREAD

**Issue by ayushi-nyk** [w3c/webdriver-bidi#366]
I am getting below error in my eclipse -
The type org.openqa.selenium.bidi.HasBiDi cannot be resolved. It is indirectly referenced from required .class 
 files

Below are the dependencies version used -
Selenium Version - 4.7.2
selenium api - 4.6
selenium remote - 4.6
selenium support - 4.4 

Please suggest .

**Comment by pujagani** [comment]
This issue seems to be specific to Selenium and not the w3c BiDi protocol itself. Please create an issue in the Selenium repo with all the necessary details.
