### ISSUE TITLE
Ambiguity in margin property of browsingContext.print parameters

### ISSUE THREAD

**Issue by jimevans** [w3c/webdriver-bidi#369]
The CDDL for `PrintParameters` specifies the property name for margins to be `margin`. The prose text seems to imply that it should be `margins`. These should be reconciled. The correct property name feels like it should be `margins` in the CDDL, absent a compelling reason it should be otherwise.

**Comment by whimboo** [comment]
Note that [WebDriver classic also uses `margin`](https://w3c.github.io/webdriver/#print-page) as object. So we probably don't want to have a different format but might want to update the prose instead? @jgraham

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/370

**Comment by whimboo** [comment]
#370 has been merged. Thanks for reporting @jimevans!
