### ISSUE TITLE
Deserialize shared reference should probably raise a "no such node" error if origin doesn't match

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#376]
Currently the BiDi spec says:

> If node’s [node document](https://dom.spec.whatwg.org/#concept-node-document)'s [origin](https://dom.spec.whatwg.org/#concept-document-origin) is not [same origin domain](https://html.spec.whatwg.org/multipage/browsers.html#same-origin-domain) with environment settings’s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin) then return null.

https://w3c.github.io/webdriver-bidi/#deserialize-shared-reference

If we return `null` as given our deserialization approach would be to continue with [`deserialize remote object reference`](https://w3c.github.io/webdriver-bidi/#deserialize-remote-object-reference). If a `handle` is available and it would certainly not be available in the specified context, we return a `no such handle` error.

Given that we prioritize `sharedId` if given we should not fallback to `handle`.

CC @jgraham, @sadym-chromium

**Comment by sadym-chromium** [comment]
agree

**Comment by whimboo** [comment]
Thanks! I'll come up with a PR tomorrow and will fix it as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1770733 given that it's still in review.

**Comment by whimboo** [comment]
Actually we moved out the origin checks to https://bugzilla.mozilla.org/show_bug.cgi?id=1806788 as follow-up.
