### ISSUE TITLE
"browsingContext.captureScreenshot" should support different image formats

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#383]
As of now we only support PNG. It would be great if at least JPG would be supported as well. With that addition a `quality` parameter might be helpful as well.

**Comment by OrKoN** [comment]
Puppeteer also needs/supports webp.

**Comment by thiagowfx** [comment]
Reference: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

**Comment by whimboo** [comment]
@jrandolf would you mind adding some wpt tests for this new feature?
