### ISSUE TITLE
Should `log.entryAdded` events only be send for Console API calls that use the Printer?

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#393]
As @OrKoN brought up to me yesterday there is a Puppeteer test (using BiDi) failing for Firefox because we send out a `log.entryAdded` event for the `console.time()` call:

```
2023-03-28T17:32:37.361Z puppeteer:webDriverBiDi:RECV ◀ [
  '{"method":"log.entryAdded","params":{"type":"console","method":"time","source":{"realm":"6442450945","context":"08af85d7-1bca-46c4-8ddb-87aa38cf71f4"},"args":[{"type":"string","value":"calling console.time"}],"level":"info","text":"calling console.time","timestamp":1680024757358}}'
]
2023-03-28T17:32:37.361Z puppeteer:webDriverBiDi:RECV ◀ [
  '{"method":"log.entryAdded","params":{"type":"console","method":"timeEnd","source":{"realm":"6442450945","context":"08af85d7-1bca-46c4-8ddb-87aa38cf71f4"},"args":[{"type":"string","value":"calling console.time"}],"level":"info","text":"calling console.time","timestamp":1680024757360}}'
]
```

When reading the WebDriver BiDi spec it is not clear if console API calls that don't use the printer should be ignored (like in Chrome) or not. I think we have to reach consensus here to one or the other behavior.

**Comment by OrKoN** [comment]
I can see how printing both messages (the current Firefox behaviour) could be useful for client implementations but it might be a blocker on the CDP side (if a message is not added to the console, it is probably discarded and just adding it would affect existing clients.) cc @sadym-chromium

**Comment by whimboo** [comment]
From the meeting on April 12th:
> <jgraham> jgraham: Next step is to figure out if there are implemenation constraints i.e. whether other implementations could be changed to always send events, since that seems more flexible.

@mathiasbynens and @gsnedders would you mind checking if browsers beside Firefox could send out events for console API calls and not only those that actually print? Thanks!

**Comment by whimboo** [comment]
> @mathiasbynens and @gsnedders would you mind checking if browsers beside Firefox could send out events for console API calls and not only those that actually print? Thanks!

@mathiasbynens and @gsnedders I want to ask if you had the time to check if that is possible in Chrome and Safari. Thanks!

**Comment by mathiasbynens** [comment]
@sadym-chromium You’ve worked on BiDi logging in Chrome before — could you find this out please?

**Comment by OrKoN** [comment]
When are the following steps invoked https://w3c.github.io/webdriver-bidi/#event-log-entryAdded ?

**Comment by OrKoN** [comment]
CDP does not emit a console message for console.time and we have no good way to implement it for only BiDi as it's part of V8 and changes would affect DevTools and many other clients. What do you think about changing the console patch section to something like:

> If that method does not call the [Printer](https://console.spec.whatwg.org/#printer) operation, return.

> Otherwise, at the point when the [Printer](https://console.spec.whatwg.org/#printer) operation is called with arguments name, printerArgs and options (which is undefined if the argument is not provided), call any [console steps](https://w3c.github.io/webdriver-bidi/#console-steps) defined in external specification with arguments name, printerArgs, and options.

**Comment by sadym-chromium** [comment]
> @sadym-chromium You’ve worked on BiDi logging in Chrome before — could you find this out please?

**Comment by whimboo** [comment]
In our current DevTools client console code we currently ignore those Console API calls to stay in sync with Chrome. That means that for now it should be fine as well for WebDriver Bidi.

@OrKoN would you mind opening a PR for the proposed wording?
