### ISSUE TITLE
Add events for History API usage

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#402]
The BiDi events monitoring navigation and page load are not triggered when using the `history` API.
"history" navigations are quite different from real navigations, so it probably makes sense to avoid emitting the regular navigation events for those.

However it could be interesting to at least add a new event triggered when `popstate` is emitted by the History API. For instance, CDP offers the `Page.navigatedWithinDocument` event which is emitted in this case.

The `BrowsingContext` module could be a good fit for this new event.

**Comment by juliandescottes** [comment]
@OrKoN can you share if `Page.navigatedWithinDocument` is important to support for puppeteer? I can see a few hits in the puppeteer codebase, but not sure how critical that is for you?

**Comment by OrKoN** [comment]
In Puppeteer, we try to treat same-document navigations the same way as regular navigations. We use navigatedWithinDocument for this. For example, using the history API or navigating to `page#hash` would be treated as a navigation in Puppeteer.

**Comment by OrKoN** [comment]
Relevant parts of the code https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Frame.ts#L335

**Comment by whimboo** [comment]
> Relevant parts of the code https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Frame.ts#L335

@OrKoN, I assume that you accidentally pasted a different link here? This one goes to `childFrames`.

**Comment by OrKoN** [comment]
To clarify: the support for `Page.navigatedWithinDocument` (or an alternative way to get events about same document navigations) is important to Puppeteer.

**Comment by jgraham** [comment]
Isn't that `browsingContext.FragmentNavigated`?

**Comment by OrKoN** [comment]
I think it might be it: perhaps not implemented by the implementations yet?

**Comment by OrKoN** [comment]
I think it is covered by this algorithm https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-fragid (step 17.2)?

**Comment by whimboo** [comment]
Yes, it's not implemented in Firefox yet. I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1841039.

@OrKoN does Chrome / CDP have it? Does it work as expected? If yes we potentially can close this issue.

**Comment by OrKoN** [comment]
I think it is implemented in chromium-bidi. Perhaps we need to add some WPT tests?

**Comment by whimboo** [comment]
Yes, wdspec tests are missing for this event. Could someone from Google may implement those? I'm happy to review, and to include our implementation for the next milestone.

**Comment by OrKoN** [comment]
let me take this (I will close the issue once the WPT test have landed)

**Comment by whimboo** [comment]
> let me take this (I will close the issue once the WPT test have landed)

Which wpt tests do you reference here? Those for [`browsingContext.fragmentNavigated`](https://github.com/web-platform-tests/wpt/pull/40813)?

**Comment by OrKoN** [comment]
yes

**Comment by OrKoN** [comment]
From my perspective, the current test set is sufficient (it only tests basic history API functions ) though but we already adjusted our implementation so it passes the tests. Unless someone sees a need for more History API tests, I would close now.

**Comment by whimboo** [comment]
We can / will certainly add more tests but this wouldn't require any new event for WebDriver BiDi. As such we can indeed close this issue.
