### ISSUE TITLE
Ability to ignore SSL errors

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#416]
It seems useful to have an equivalent of Security.setIgnoreCertificateErrors for ignoring certificate errors when testing in a test/local setup.

**Comment by jgraham** [comment]
That can already be done with capabilities: https://w3c.github.io/webdriver/#dfn-insecure-tls-certificates Do you need to be able to set that at runtime or just globally while the browser is under automation?

**Comment by OrKoN** [comment]
Good point, it's called acceptInsecureCerts in the bidi spec. My keyword search failed me :)
