### ISSUE TITLE
Ability to get the user agent 

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#446]
In CDP, `Browser.getVersion` returns `userAgent` fields that are used by Puppeteer for  https://pptr.dev/api/puppeteer.browser.useragent which allows getting the user agent without a need for any browsing contexts to exist.

Does it make sense to add it to WebDriver BiDi? (perhaps, as the result of session.new command)

**Comment by christian-bromann** [comment]
Aren't these information already available? The exact browser version is returned by e.g. Chromedriver when a session is initiated. The user agent can be retrieved by an [`evaluate`](https://w3c.github.io/webdriver-bidi/#command-script-evaluate) command.

**Comment by OrKoN** [comment]
@christian-bromann I suspect the evaluated command would return the emulated user agent and requires a page (browsingContext) to be working? Thanks for the pointer about the [version](https://w3c.github.io/webdriver-bidi/#command-session-new), overlooked that!

**Comment by christian-bromann** [comment]
> I suspect the evaluated command would return the emulated user agent and requires a page (browsingContext) to be working?

I am not entirely sure about the differences about an emulated and actual user agent, nor how this impacts the use case you are going for.

**Comment by OrKoN** [comment]
The difference is that Browser.getVersion returns the user agent that is computed by the browser by default or configured via command line arguments and evaluation of a script might return the user agent that is emulated https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride (Emulation of the user agent is probably smth that will have to be discussed separately.).

P.S. I have updated the issue based on the info you provided, thanks!

**Comment by whimboo** [comment]
What about returning the original user agent as part of the new session capabilities? Could that be an option? It would have to be retrieved only once anyway given that it is static.

**Comment by OrKoN** [comment]
That would work!

**Comment by whimboo** [comment]
@jgraham when remote ends return the user agent via the capabilities, does it require a spec change? Probably yes given that it will not be a vendor specific capability.
