### ISSUE TITLE
Specify a Logging module

### ISSUE THREAD

**Issue by mjzffr** [w3c/webdriver-bidi#45]
WebDriver BiDi should have a Logging module to make it easy to monitor messages logged from various sources. This module might be a good candidate for early prototyping.

In practice, we've seen test automation assert that there is no logging to the console at all, or failing if there's any message text that matches a certain pattern, which brings pitfalls with any browser-specific log output.

The protocol should distinguish different kinds log entries and allow filtering based on various criteria to further reduce traffic over the websocket.

One event:

* `logEntryAdded`. Some possible parameters:
  * `level` (String): e.g. info
  * `text` (String): the log message
  * `kind` (String): is it a Console API call, a kind of error or warning (CSS, JS, security), a network request?
  * `scriptContextId` or `browsingContextId` for which this log entry was added
  * `timestamp` (number)
  * `extra` (object): additional optional metadata that applies to different _kinds_ of log entries
    * `url`: resource URL for which this log entry was added
    * `args`: Console API call args
    * `method`: Console API method called
    * `lineNumber`
    * `colNumber`
    * `requestId`: network request ID
    * `bootstrapScriptId` if the entry originated from a [bootstrap script](https://github.com/w3c/webdriver-bidi/blob/master/proposals/bootstrap-scripts.md)

In addition to being able to subscribe to the `logEntryAdded` event, we should be able to narrow down the subscription with filters like the `kind`, a `url` prefix, `scriptContextId`, whether it's from a bootstrap script...

Maybe the general [subscribe](https://github.com/w3c/webdriver-bidi/blob/master/proposals/core.md#events) method could have a `match` parameter to specify such filters along the same lines as the [match patterns](https://github.com/w3c/webdriver-bidi/blob/master/proposals/bootstrap-scripts.md#match-patterns) in the bootstrap-scripts proposal.

**Comment by shs96c** [comment]
This seems focused on console-style logs (that is, not things like network performance), and I like the approach. Logging came up a few times in the f2f sessions while working on the original webdriver spec. There was a [discussion in 2013](https://www.w3.org/2013/06/13-testing-minutes.html#item02) and a [later one in 2017](https://www.w3.org/2017/11/10-webdriver-minutes.html#item01)

In addition, the Selenium project has a logging API that is already implemented by the chromedriver. Michael Klepikov gave a talk about how to use this at [GTAC in 2013](https://www.youtube.com/watch?v=0_kAPWSZNY4) too. The underlying APIs are [here in the selenium source](https://github.com/SeleniumHQ/selenium/tree/selenium-4.0.0-alpha-6/java/client/src/org/openqa/selenium/logging). The key classes being [Logs](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-6/java/client/src/org/openqa/selenium/logging/Logs.java) and [LogEntry](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-6/java/client/src/org/openqa/selenium/logging/LogEntry.java)

While these APIs should be event-based in webdriver bidi, there are some basic concepts that might be nice to consider as we add these capabilities to WebDriver bidi:

* Can select the types of logs to collect
* Allows logs from intermediary nodes to be collected

The ability to introspect into more than just the end node can be a really useful feature.

**Comment by foolip** [comment]
One kinds of logs that have come up in browser testing is the stdout/stderr of the browser itself, used to get stack traces if there's a crash. Is this something we'd consider in scope for this? cc @stephenmcgruer

**Comment by jgraham** [comment]
So to summarise the discussion, I think there's general agreement that the design here is the right start. There seems to be a preference for the name `Console` vs `Logging`. There's also a concern that new types of log events are added frequently, so we should ensure that the design is extensible, and can support vendor-specific event types. There's also a question about how to implement filtering by type or level since some sites can produce many log messages; that might need to be a seperate state-setting command.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/73 has an early cut of this

**Comment by jgraham** [comment]
The initial PR landed, so I'm going to close this even though there's more to be done.
