### ISSUE TITLE
Require some minimum message size to work?

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#48]
In [Design Proposal for ChromeDriver establishing BiDi WebSocket connection](https://docs.google.com/document/d/1zixFBPtgFFwhc5pT1IfneFoW6yZfpvYdQRsNN4tbghk/edit?disco=AAAAKFgChu4) @k7z45 noted that the WebSocket implementation in Chromium has [256 MB](https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/server/chromedriver_server.cc;l=59;drc=23f61cb65a94208dc2c4728e895e87d47f64a8b6) limit on messages sent and received.

That's a large limit, and the upper limit should probably be treated as a quality of implementation question as is typically done for things like URL lengths, `<canvas>` size, image size, etc.

However, should we have a minimum message size to support that we test in web-platform-tests, so that clients can depend on that working?

**Comment by foolip** [comment]
Perhaps as a start we could figure out what the size of a full size screenshot for an 8K monitor would be, and round up a bit from there.

**Comment by foolip** [comment]
While not the same kind of limit in the same kind of place, https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#url-length says that URLs are limited to 2MB in Chrome.

**Comment by burg** [comment]
I don't understand the reason for this issue to exist. It sounds like you are saying we need a minimum message size so we can write a test to check it. Is there a product or user facing reason for this work?

**Comment by foolip** [comment]
Writing and passing tests is not a goal in itself, no.

What clients might come to depend on is a certain size of a command working, but we haven't discussed any commands taking a potentially large parameter. One could maybe see it in an API to intercept and replace network responses, which is mentioned in https://github.com/w3c/webdriver-bidi/blob/master/explainer.md#goals, but we haven't discussed a design.

For responses, like large screenshots, the problem is not very plausible: that an implementation could generate a (say) 10 MB screenshot in memory but fail its own limit on message size and refuse to send it.

I'm happy to revisit this when we define commands with potentially large parameters. When we do, we might learn that no implementation has a limit <10 MB anyway and it will never be an issue.

**Comment by whimboo** [comment]
Note that CDP supports chunking of huge payloads by using the [IO domain](https://chromedevtools.github.io/devtools-protocol/tot/IO/). Clients can then read the data from a stream. Puppeteer for example always returns a stream for eg. [print as PDF](https://github.com/puppeteer/puppeteer/blob/ffec2475d0cae61ddb4d6d32956408afe836552e/src/common/Page.ts#L1770). 

But beside that I haven't seen anything around a minimum message size yet.
