### ISSUE TITLE
Sending a webSocket URL to the client isn't really necessary 

### ISSUE THREAD

**Issue by bwalderman** [w3c/webdriver-bidi#49]
In [Establishing a Connection](https://w3c.github.io/webdriver-bidi/#establishing), we currently [construct a WebSocket URL](https://w3c.github.io/webdriver-bidi/#construct-a-websocket-url) with a host, port, and session ID, and return this URL to the client in the `webSocketUrl` property of the new session capabilities.

If we were to specify that all websocket URLs follow a known pattern instead, then the client can simply connect to ws://host:port/session/<sessionId>, and there is no need for the remote end to tell the client what this URL is. This is more in line with how traditional WebDriver endpoints work. For example, the client just knows what the proper endpoint is for sending a `Find Element` command for a particular session.

If we decide to support bidi sessions without going through HTTP first, as proposed in #46, then a well-known websocket URL will come in handy here too. For example, we might define a global websocket endpoint where clients can send "status" and "new bidi session" commands to.

Proposal:
- Specify the path for a websocket URL for a session to be /session/<sessionId>
- Return a boolean for the `webSocketUrl` capability that indicates whether bidi is supported. Probably rename it to `bidi` while we're at it.
- If `bidi` is true, then the remote end will accept websocket connections at /session/<sessionId>

**Comment by jgraham** [comment]
I think that well-known urls have a share of problems and I think we should avoid them here. Making the URL well-known means that implementations don't get the freedom to choose a free port to listen on, increasing the chance of conflicts. It also gives more flexibility to setups where a single machine handles multiple connections.

For implementations that want to support direct connections without the initial HTTP connection, I think it should be communicated out of band e.g. if you do `browser --webdriver` it could launch the browser with the listener enabled and write the websocket url to stdout.

**Comment by jgraham** [comment]
Also, in terms of path, I think it is specified that you need to provide a session id in the path. I agree that for the no-initial-HTTP case we will need some way to establish a session and vend a session id. I think that's largely unrelated to whether the initial URL is well-known or has to be communicated in some way.

**Comment by JohnChen0** [comment]
For ChromeDriver and EdgeDriver, it's easy for the client app to construct WebSocket URL, since the implementation will share the same TCP/IP port for HTTP and WebSocket connections. But it's also conceivable that some WebDriver BiDi implementations may use different libraries for HTTP server and WebSocket server, and thus requiring different ports. In this case, it would be impossible for the client app to construct the WebSocket URL without additional information (i.e., the WebSocket port). Letting the implementation return the WebSocket URL to client app is more flexible.

**Comment by foolip** [comment]
Aside: the name of the capability changed from `bidi` to `webSocketUrl` after my bikeshedding in https://github.com/w3c/webdriver-bidi/pull/24#discussion_r434879836

**Comment by shs96c** [comment]
Sending the URL allows intermediate nodes or "WebDriver as a Service" to sensibly rewrite the initial payload, possibly redirecting to different infrastructure.

**Comment by jgraham** [comment]
I'm going to close this without making a change; I think there's general consensus that the additional flexibility and explictiness in the current system is valuable.
