### ISSUE TITLE
Changing the master branch to main?

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#490]
It seems like main is more common nowadays and I often find the master branch used in this repo (and in WPT) to be an exception for repositories I frequently work with. Let's change the main branch to be called main for this repo?

cc @mathiasbynens @jgraham

**Comment by jgraham** [comment]
Yes, that's fine by me for this repo (wpt is substantially more complex because there's a lot of tooling with the branch name hardcoded; we put together a transition doc at some point but it didn't get priority).

**Comment by OrKoN** [comment]
@jgraham are you able to do that or do we need to involve someone else? from our side, I don't think we have any dependency on the main branch name. In this repo, a few scripts have to be updated but looks like that's it.
