### ISSUE TITLE
Meta: WebDriver BiDi extensions

### ISSUE THREAD

**Issue by mathiasbynens** [w3c/webdriver-bidi#506]
WebDriver Classic allowed other specs & vendors to define [extension commands](https://w3c.github.io/webdriver/#extensions-0) and [capabilities](https://w3c.github.io/webdriver/#dfn-additional-webdriver-capability).

Similarly, WebDriver BiDi allows [extension modules](https://w3c.github.io/webdriver-bidi/#extension-modules). Let’s use this issue to track such modules in other specs and repos:

- [x] https://github.com/WebBluetoothCG/web-bluetooth/issues/613

**Comment by OrKoN** [comment]
cc @mathiasbynens @whimboo should we track extensions via this issue or have it on the space page?

**Comment by whimboo** [comment]
What is the `space page`?

**Comment by OrKoN** [comment]
@whimboo sorry, a typo, I meant to be "spec" (i.e., https://w3c.github.io/webdriver-bidi/)
