### ISSUE TITLE
Extend `browsingContext.Info` with `opener`

### ISSUE THREAD

**Issue by Lightning00Blade** [w3c/webdriver-bidi#516]
In CDP there is a concept `opener` exits related to new Windows/Tab being open from another Window/Tab.
Puppeteer also supports this for CDP via the `page.on('popup')`.
Ref [CDP TargeInfo](https://chromedevtools.github.io/devtools-protocol/tot/Target/#type-TargetInfo)

The proposed solution would be add a property on the `browsingContext.Info Type` called `opener`, that will be `browsingContext.BrowsingContext / null`  of either the browsing context or the top level browsing context.

Example of such scenarios:

-  evaluation of `window.open('about:blank')`.
- clicking a anchor `<a target=_blank href="/">open</a>`.

**Comment by OrKoN** [comment]
Sounds reasonable to me.

**Comment by OrKoN** [comment]
cc @jgraham @whimboo @juliandescottes do you have any concerns about this?

**Comment by jgraham** [comment]
This seems fine.

**Comment by OrKoN** [comment]
I think the difficultly here is that when the HTML spec calls the algorithm to emit the browsing context create event, there is no original opener ID available in that algorithm and I am not sure what is the best way to make it available. Note that Puppeteer requires an opener ID even if the browsing context is loaded with noopener=true. There is a place for saving the original opener after the context is created but it is too late for including it in the created event: https://github.com/w3c/webdriver-bidi/pull/664

**Comment by jgraham** [comment]
In gecko this is easy to implement in the case that we have `window.opener` but hard in cases where `window.opener` is null (in that case we discard knowledge of the original opener early, like the spec). So a question is how much of the use case here depends on always having opener, vs only having it in cases where `window.opener` exists.

**Comment by Lightning00Blade** [comment]
The PR for this has already landed, closing.
