### ISSUE TITLE
What are the requirements for a command id?

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#52]
Each command has a command id that's an integer allowing the client ("local end") to identify which response corresponds to which command. But it's not clearly specified what requirements there are on this id and how they are enforced. Presumably the id is supposed to be unique. Is it supposed to be monotonically increasing? That allows the remote end to reject messages with a possibly-reused id only storing a single integer, but also requires that the client serializes all messages through a single process. In particular it doesn't allow some architecture in which multiple independent processes write commands to the same websocket. That's probably fine, and if we really want something like that we could revisit supporting multiple connections. But I want to check there's not some reason to allow non-monotonic command ids.

**Comment by foolip** [comment]
The setup I've had in mind is to allow the client to use any integers it likes in any order it likes, and only require the remote end to use it in the response.

The implication of this is that the remote end can't use the ID to identify in-progress commands internally, but will need its own unique identifier, which if it isn't just a pointer will require a few bytes of extra memory.

If ensuring unique identifiers would be useful to implementations, then the simplest rule I can see is monotonically increasing per session, where the code that processes and dispatches incoming messages keeps track of the largest id seen so far. But requiring that (and testing it) would need to have some real benefits elsewhere to justify, IMHO.

**Comment by jgraham** [comment]
I suppose that makes sense. But if that's the case we should call out in the spec that it's an error for a remote end to rely on the command id being unique.

**Comment by foolip** [comment]
Indeed we should update the spec whichever way we go.

**Comment by gsnedders** [comment]
What happens if the remote end fails to respond to commands in flight? Because, e.g., it's having difficulty contacting the appropriate browser process? What does the client do when there's no more command IDs?

**Comment by jgraham** [comment]
Is running out of JSON-representable (or even 32-bit) integers a realisitc problem? If the remote end is failing to respond to that number of commands we likely have bigger issues.

I tend to agree with foolip that the spec should say that these numbers are opaque to the server and it's up to the client to provide command ids that it can usefully use to distinguish in-flight commands.

**Comment by jgraham** [comment]
I added a note in https://github.com/w3c/webdriver-bidi/pull/50 to call out the fact that the command id isn't necessarily unique.

**Comment by gsnedders** [comment]
> Is running out of JSON-representable (or even 32-bit) integers a realisitc problem? If the remote end is failing to respond to that number of commands we likely have bigger issues.

32-bit integers can be iterated through in <1s on a modern CPU; yes, it's somewhat unlikely that you'll be dispatching them that quickly, but it's likely on an order of magnitude that can be hit.

53-bit integers would take over 20 days on a modern CPU, which is much more unlikely.

Either way, I think we can say that "if there are no more available command IDs, the client must drop the connection and abort with an error".

**Comment by jgraham** [comment]
Historically we haven't put any requirements at all on clients. I'm not convinced that adding a requirement to drop the connection if you have (even just) 2**32 commands in flight simultaneously is useful enough to change that stance. Such a requirement doesn't help the browser at all since a client can ignore it, and doesn't really help clients since they typically aren't going to notice that the spec tries to mandate behaviour for a rare edge case.

**Comment by shs96c** [comment]
The command id could be something other than a number: an opaque string would be fine too, and could be of effectively unlimited length.

**Comment by shs96c** [comment]
To expand on my somewhat cryptic comment above :) 

Taking this back to @jgraham's original comment: 

> Each command has a command id that's an integer allowing the client ("local end") to identify which response corresponds to which command

The `id` is simply a mechanism to correlate messages and responses. There is no need for this to be a number, so long as the values are the same, and the same correlation implies that no `id` is ever reused. The simplest way to do this is with a number that keeps increasing monotonically (as [pointed out](https://github.com/w3c/webdriver-bidi/issues/52#issuecomment-688464620) by @foolip) but this is impractical if we expect a session to be very long-lived (as @gsnedders [points out](https://github.com/w3c/webdriver-bidi/issues/52#issuecomment-689714386))

My suggestion would be for the local end to be responsible for generating the `id`, but to limit the type of the `id` to a number or a string. However, it doesn't look as if CDDL and CBOR allow that kind of thing. Since we know that the number types are not appropriate, we're left with the string type as the best choice.

This implies we'll need some language in the spec to ensure that message IDs are unique, and how to handle the case where an ID is reused (we may well need that language in any case)

**Comment by jgraham** [comment]
I think we actually solved this one. We could use "number or string" or we could just use "string". But in the spec right now there's no uniqueness requirement; the command id is just copied from the command onto the relevant response. So maintaining a unique-enough mapping is a client problem; basically it's up to you to ensure that you don't reuse a command id you already sent. Even if that was only 2**32 possible ids, I'd think it's not a problem we're likely to run into for a naive client that doesn't reuse ids, assuming it's actually 2**53 makes it almost impossible.

I think we should close this issue and if there's a remaining concern about integer ids let's have a new issue or pr about using strings instead.
