### ISSUE TITLE
CSS pixels for scrolling

### ISSUE THREAD

**Issue by jrandolf** [w3c/webdriver-bidi#520]
Currently BiDi doesn't specify whether scrolling uses hardware pixels or CSS pixels. Based on current implementation, it seems like we want hardware pixels.

**Comment by whimboo** [comment]
For a [`pointer move` action](https://w3c.github.io/webdriver/#dfn-dispatch-a-pointermove-action) in the WebDriver classic specification we define value like:

> If x is less than 0 or greater than the width of the viewport in [CSS pixels](https://w3c.github.io/webdriver/#dfn-css-pixels), then return [error](https://w3c.github.io/webdriver/#dfn-error) with error code [move target out of bounds](https://w3c.github.io/webdriver/#dfn-move-target-out-of-bounds).

To stay compatible with classic WebDriver BiDi also has to use CSS pixels and not screen pixels.

**Comment by jrandolf** [comment]
Turns out there was a bug in Chromium. Fixed in https://chromium-review.googlesource.com/c/chromium/src/+/4813942
