### ISSUE TITLE
Web Extensions: install / uninstall

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#548]

**Comment by whimboo** [comment]
This topic has been discussed at TPAC 2023. The minutes can be found at:
https://www.w3.org/2023/09/15-webdriver-minutes.html#t04

**Comment by whimboo** [comment]
Maybe the definition of extensions in the capabilities could look like the following:

```
{
  "extensions": [
    "<base64_encoded_extension>",
    {"extension": "<base64_encoded_extension>", "installTemporary": true, "allowPrivateBrowsing": true},
  ],
}
```

That means by default extensions could be listed as usual as a list of base64 encoded strings, or if more options are needed for the install process an object could be passed with additional flags - all of them optional and default to false?

**Comment by OrKoN** [comment]
CDP now supports loading unpacked extensions at runtime https://chromedevtools.github.io/devtools-protocol/tot/Extensions/#method-loadUnpacked (with some restrictions such as a special flag + pipe connection)

**Comment by whimboo** [comment]
Fixed by https://github.com/w3c/webdriver-bidi/pull/778.
