### ISSUE TITLE
Network Intercept: continue response: specifying only "status" or "headers"

### ISSUE THREAD

**Issue by thiagowfx** [w3c/webdriver-bidi#572]
I just learned that CDP does not support executing ["continue response"](https://w3c.github.io/webdriver-bidi/#command-network-continueResponse) with only one of either `status` or `headers` (c.f. [here](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/fetch_handler.cc;l=347;drc=1de2a0e4f42811d2f06ec12b6b5147a35d279f72)) i.e. both should be provided.

This prompted me to file this issue to request clarification w.r.t. the spec. The questions are:

1. Is this the desired behavior? If yes, then we should add an assertion to the spec, and possibly throw "invalid argument" in this scenario.
2. If no, then what should be remote behavior be? The most straightforward one seems to reuse the pre-existing value. For example: If the client tries to continue response with a custom header, then we automatically populate the status code value to what it would be had the response not been intercepted. And vice-versa in case there's a status code but not a header.

What is the correct intended / expected behavior here?

cc @juliandescottes @jgraham

**Comment by thiagowfx** [comment]
cc @sadym-chromium

**Comment by sadym-chromium** [comment]
I read the spec as "if user don't specify `status` or `headers`, the ones from the original response should be provided". And from the implementation side we should already have the original response status and headers, so if we want to override only one of them, we provide another with the original value.

**Comment by thiagowfx** [comment]
This is basically 2). OK. Let me wait for a few more days to see if anyone disagrees.

**Comment by sadym-chromium** [comment]
> This is basically 2). OK. Let me wait for a few more days to see if anyone disagrees.

Spec-wise, [`update the response`](https://w3c.github.io/webdriver-bidi/#update-the-response) has a response, which is not null in case of `continueResponse`, so the further manipulations are done on the original response and overridesome of the original properties.

**Comment by Lightning00Blade** [comment]
I think the spec definition mentioned by @sadym-chromium is correct, so closing as non actionable.
