### ISSUE TITLE
Command response: "value" or "result"?

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#58]
In https://github.com/w3c/webdriver-bidi/pull/50, the `CommandResult` CDDL definition was added, with "value" as the property to hold the result of a successful command. I noticed this and suggested changing it in https://github.com/w3c/webdriver-bidi/pull/56#discussion_r497361766, but moving to a separate issue.

https://www.jsonrpc.org/specification uses "result" and in https://github.com/w3c/webdriver-bidi/issues/14#issuecomment-633568306 and https://github.com/w3c/webdriver-bidi/issues/14#issuecomment-633581820 I provided samples of Chrome and Safari's devtools/inspector protocols showing that they also use "result".

Although it will not be possible to use existing libraries for JSON-RPC or existing devtools/inspector protocols with WebDriver BiDi, I would like to match existing protocols where it is of no consequence and only a matter of picking a name. So I am suggesting that we use "result".

**Comment by shs96c** [comment]
The discussion in #14 suggests that `result` is the appropriate response to use. This is inline with existing browser debugging protocols, and with JSON-RPC.

**Comment by whimboo** [comment]
And this was done as part of PR #62 quite a while ago.
