### ISSUE TITLE
Umbrella / Meta: Browser Permissions as an extension module

### ISSUE THREAD

**Issue by thiagowfx** [w3c/webdriver-bidi#587]
Permissions spec umbrella issue: https://github.com/w3c/permissions/issues/424

- [x] [(optionally) add a recommendation about how external specifications should be authored (e.g., defining complete modules). I think we can leave the text about implementation extensions as is. It looks like there is nothing blocking on the WebDriver BiDi spec side](https://github.com/w3c/permissions/pull/425#discussion_r1386603368): https://github.com/w3c/webdriver-bidi/pull/605

"Interacting with Permissions for Powerful Features"

The [**WebDriver BiDi spec**](https://w3c.github.io/webdriver-bidi/) spec should support interaction with **browser permissions** as an [extension module](https://w3c.github.io/webdriver-bidi/#extension-modules). These permissions represent a user's choice to allow or deny access to "powerful features" of the platform. For developers, the specification standardizes an API to query the permission state of a powerful feature, and be notified if a permission to use a powerful feature changes state.

The Permissions spec already supports [WebDriver classic](https://www.w3.org/TR/permissions/#set-permission-command). This bug is about making it support [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) as well.

References:

- W3C Permissions spec: https://www.w3.org/TR/permissions/
- W3C Permissions repo: https://github.com/w3c/permissions/

Soft references:

- https://github.com/w3c/webdriver-bidi/issues/506
- https://github.com/w3c/webdriver-bidi/pull/523

**Comment by whimboo** [comment]
> The Browser Testing and Tools Working Group just discussed `Permission extensions`.
> The full IRC log of that discussion

And there was one more comment from @jgraham that actually sneaked into the logs for https://github.com/w3c/webdriver-bidi/issues/287#issuecomment-1802375543:

> <jgraham_> (don't want to extend this topic further, but I always assumed BiDi would move to an event-based model for permissions i.e. you'd get a permissions.Request event with some information)

**Comment by thiagowfx** [comment]
The recommendation was added (https://github.com/w3c/webdriver-bidi/pull/605), and the umbrella issue in the permissions repo was closed (https://github.com/w3c/permissions/issues/424), therefore this can be closed.

I'll just note that there's one missing AI from https://github.com/w3c/permissions/issues/424:

>  TODO: Add `user context` to `SetPermissionParameters`

@OrKoN you may want to open a separate bug/FR for that, if still relevant
