### ISSUE TITLE
blocked requests map is only cleared in network.beforeRequestSent

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#615]
Network events can be intercepted in several phases: beforeRequestSent, authRequired, responseStarted. If a request is intercepted, it gets added to a blocked requests map.

At the moment this entry is only cleared after the request is handled in the `beforeRequestSent` phase with 

> [Remove](https://infra.spec.whatwg.org/#map-remove) blocked requests[request id].

For authRequired and responseStarted, I don't think the map entry ever gets removed? cc @jgraham

**Comment by whimboo** [comment]
This indeed looks like a bug. @jgraham could you please verify? Thanks.
