### ISSUE TITLE
Define a default value for "width" and "heigh" on pointer input sources

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#646]
There is currently a discrepancy between Chrome and Firefox which results in different radius values for x and y for the `touch` related events as fired by the browser. While Chrome reports `0.5` in Firefox `1` is reported because [it's getting set here](https://searchfox.org/mozilla-central/rev/a2709c2f0e31b2ad1a7b6447117626a34063fe57/remote/shared/webdriver/Actions.sys.mjs#2310-2311). 

As such a default value would be good to have.

CC @jgraham

**Comment by whimboo** [comment]
In WebDriver BiDi we actually have the default set to `1` in the `input.PointerCommonProperties` type definition. I think that this satisfies the need here.

Not sure why Chrome uses 0.5 but maybe it does it on HiRes devices? We should figure out what to do in case of emulating the device pixel ratio. 

CC @OrKoN @sadym-chromium

**Comment by OrKoN** [comment]
@whimboo could you please link the test you used that demonstrates the difference?

**Comment by whimboo** [comment]
Sure it's https://github.com/puppeteer/puppeteer/blob/b53de4e0942e93cbc5a5dd7a46b59bab56f06c92/test/src/touchscreen.spec.ts#L40. The other test in this file fails because no `click` event is sent (but that's a different issue).

**Comment by jrandolf** [comment]
We already have a default set to 1 for width and height. Firefox is incorrectly implementing the radiusX and radiusY; in particular, the radius is half the diameter which in this case is 1, so the radiusX and radiusY should be 0.5
