### ISSUE TITLE
Specify a network request interception feature

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#66]
A common use case for automation is to take a request that would be made e.g. to a third party API and provide a mock response for that reques, or to take a request that requires HTTP authentication and automatically provide that authentication. This is a feature that's exposed in [Puppeteer](https://github.com/puppeteer/puppeteer/blob/v5.4.1/docs/api.md#httprequestrespondresponse) and is in the works for Selenium.

The existing CDP API is the [Fetch domain](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/). Something similar has been added to [WebKit](https://bugs.webkit.org/show_bug.cgi?id=207446). Gecko has similar features with a different API exposed to [extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest).

Given that the CDP-ish model is already widely implemented in browsers and used in clients, it makes sense to spec something close to that. Practically this means:
*  A means to enable request interception for a specific set of contexts (or realms; serviceworkers for example seem like an important use case here) and with a URL filter that's allows only intercepting a subset of responses
* An event that's produced when a request matches the filter with details about the request,  including an id that can be used to continue the request.
* A command to fulfill the request, suppliying the response headers and body.
* A (possibly seperate) command to cause a network error
* Some way to get the response that would have been returned by the network request so that it can be modified before use.

Auth seems to be handled somewhat seperately, with the following:
* An event that's fired when a request results in a HTTP auth challenge
* A command to provide the authentication response

**Comment by bobajeff** [comment]
I'm interested in having the this feature being spec'd. As Webdriver doesn't currently have an equivelant to [Network.getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getResponseBody). Which is important to me because I would like to use the feature in Firefox but it looks like [their CDP implementation is maintenance mode](https://github.com/puppeteer/puppeteer/issues/7772#issuecomment-1343980516) in favor Webdriver bidi related APIs. Until then only a fork of firefox shipped with [Playwright](https://playwright.dev/) can get response body. Which I'm uncomfortable depending on.

**Comment by jgraham** [comment]
I've started a (thusfar incomplete) draft of this feature at https://github.com/w3c/webdriver-bidi/compare/network_interception

The design at this point is as follows:
* you register an interception using `network.addIntercept`. That takes a list of URL patterns the request can match (pattern language unspecified, but probably glob-like) and a list of phases at which you want to intercept (`beforeRequestSent` / `auth` / `responseStarted`).
* Registering an interception returns an id. That can be passed to `network.removeIntercept` to disable the interception. This means that different parts of a client can independently register intercepts, and only remove the intercepts they registered (like preload scripts). The client is responsible for handling the case where there's more than one intercept registered for a specific request (see below).
* There are no new events for intercepted requests, but the existing network lifecycle events get additional fields `isBlocked` which is always sent and set to true if the request is being intercepted, and `intercepts` which is a list of registered intercepts for the request, so the client can handle the case of multiple intercepts.
* Because the same events are used, you currently need to subscribe to the relevant network lifecycle events in order for intercepts to work (if you aren't subscribed the intercept is skipped). This isn't perfect since it's not totally obvious that you need to both subscribe and also register an intercept, and because you can't currently subscribe to the events _only_ in the case that the intercept is set, so you'd have to send and discard all non-intercept network events. There is potential for optimisation here.
* The `auth` intercept phase is similar to `responseStarted`, but only when the status code and headers indicate that HTTP Auth credentials are set.
* The events block the network request until the client has responded (just once, irrespective of the number of redirects). How to organise the client's response is the biggest open question. The requirement is that we can either modify the outgoing request, or set/modify the response before it's seen by the browser. I currently expect to support modifying the request headers and body, setting the full response headers / body, or changing the response headers (in the `responseStarted` phase), plus setting the auth credentials to use for future requests. Modifying the response body is difficult with this protocol design since it either requires many back/forth events to deliver chunks of the response to the bidi client before they get to the browser, or a mechanism for allowing the browser itself to run the intercept code (e.g. sending over a function that is called with chunks of the body). So I expect to defer that to future versions of the protocol. Ignoring that, there are two obvious possible designs for responding to the intercept:
  - Multiple commands, one per action, like CDP. So to update the request we'd have `network.continueRequest`, but to set a response we'd have `network.fulfillRequest` (or similar names).
  - One command like `netwok.continueFetch`. This would allow setting either request or response properties, but it would be an error to attempt to set request properties after the request was sent. The behaviour would be determined by which fields are present in the command payload. So to just modify the request you'd set a `request` field with relevant sub-fields indicating the updated properties, whereas if you wanted to modify or fulfill the response, you'd set the corresponding `response` properties. The main question here is whether it's confusing that the actual action depends on the details of the payload parameters rather than the actual body itself. In principle this is also more flexible because you can do multiple actions at once (e.g. both modify the request headers and set credentials if you expect HTTP Auth to be required). _Maybe_ one could extend it to modifying both the request and parts of the response in the request phase (e.g. both set the request body and some response headers, whilst still going to the network for the actual response body), but that may be unnecessary.

**Comment by OrKoN** [comment]
I have double checked the current implementation in Puppeteer and here are some thoughts:

1) it would be great to allow intercepting requests for a context and related contexts (e.g., an entire tab): seems to be not in the current draft?
2) Puppeteer only supports "modifying the request headers and body, setting the full response headers / body" without "changing the response headers" or "modifying the response body" parts. CDP supports the latter two as well.
3) Having multiple commands (`network.continueRequest`, `network.fulfillRequest` and `network.failRequest`) I think is more clear but combining them into one command would also work.
4) WDYT about `isPaused` or `isIntercepted` instead of `isBlocked` for the indication of the interception? we could also rely on the presence/absence of `intercepts`, I assume?

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/429

**Comment by christian-bromann** [comment]
Has there been a consideration of enhancing this feature to allow intercepting WebSocket messages?

**Comment by whimboo** [comment]
Going to mark this issue as done based on the merge of #429 a while ago.
