### ISSUE TITLE
Clarify if Document (and other non-Element Nodes) are allowed as startNodes of browsingContext.locateNodes

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#703]
In the current spec for browsingContext.locateNodes, it is not clear if we can pass only `Element` in the `startNodes` parameter or if non-Elements (eg `Document`) are allowed.

For the accessibility and innerText locators, the spec calls other specs which only work with Elements:
- https://www.w3.org/TR/core-aam-1.2/#roleMappingComputedRole
- https://www.w3.org/TR/accname-1.2/#dfn-accessible-name
- https://html.spec.whatwg.org/multipage/dom.html#dom-innertext

Should we restrict startNodes to only contain Elements? Or should we add a special case if a `Document` is provided to use its document element?

**Comment by juliandescottes** [comment]
See #702

**Comment by OrKoN** [comment]
Shadow roots are also non-element nodes so I think the locator API is meant to accept Node's in general. We should probably make sure a11y and innerPath algorithms check the node type before performing element specific steps.

**Comment by juliandescottes** [comment]
All locators have now been updated to handle non-element context nodes correctly. Either they support it by definition (css, xpath), or logic has been added to handle them.
