### ISSUE TITLE
Support ResourceType in network requests

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#704]
CDP exposes Network.ResourceType which indicates what kind of resource is being loaded https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-ResourceType

This type of information is commonly exposed in browser DevTools and, for example, Puppeteer also exposes it to the users so that users can perform analysis and interception based on the resource type detected by the browser.

The resourceType partially matches https://fetch.spec.whatwg.org/#concept-request-destination

**Comment by OrKoN** [comment]
ResourceType vs request destination https://docs.google.com/spreadsheets/d/15nwWRnflDT8ZuoEjRbu1xqhLDXReBc4y_hV3mrQo-VE/edit?usp=sharing

**Comment by whimboo** [comment]
FYI @jgraham pushed a PR as https://github.com/w3c/webdriver-bidi/pull/809 which uses the `initiatorType` and `destination` from the fetch spec. Please let us know what you think. Thanks.

**Comment by whimboo** [comment]
https://github.com/w3c/webdriver-bidi/pull/809 is fixed.
