### ISSUE TITLE
Firefox issue with running `browsingContext.navigate` with certain preload scripts

### ISSUE THREAD

**Issue by christian-bromann** [w3c/webdriver-bidi#753]
WebdriverIO initiates some preload scripts and runs into issues when loading certain web pages. Ultimately the command fails with the following error:

```
{"type":"error","id":3,"error":"unknown error","message":"Error: NS_BINDING_ABORTED","stacktrace":"#checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:286:28\nonStateChange@chrome://remote/content/shared/Navigate.sys.mjs:345:28\n"}
```

It seems to only happen in Nightly and when these certain additional commands are called before:

```
session.subscribe {"events":["log.entryAdded","browsingContext.contextCreated","browsingContext.contextDestroyed"]}
script.addPreloadScript {"functionDeclaration":"function customElementWrapper() {\n    const origFn = customElements.define.bind(customElements);\n    customElements.define = function (name, Constructor, options) {\n        class WdioWrapperElement extends Constructor {\n            connectedCallback() {\n                super.connectedCallback && super.connectedCallback();\n                let parentNode = this;\n                while (parentNode.parentNode) {\n                    parentNode = parentNode.parentNode;\n                }\n                console.debug('[WDIO]', 'newShadowRoot', this, parentNode);\n            }\n            disconnectedCallback() {\n                super.disconnectedCallback && super.disconnectedCallback();\n                console.debug('[WDIO]', 'removeShadowRoot', this);\n            }\n        }\n        return origFn(name, WdioWrapperElement, options);\n    };\n}"}
```

I've created a reproduction case: https://github.com/christian-bromann/bidi-issue-ff .. just run `npm install` and then `node test.js`.

**Comment by OrKoN** [comment]
This probably needs to be filed at https://bugzilla.mozilla.org since it does not seem to be a spec issue? cc @whimboo

**Comment by jgraham** [comment]
Yes, please file this on bugzilla. We know we get that error in response to `browsingContext.navigate` when the page itself initiates a navigation using js during load: https://bugzilla.mozilla.org/show_bug.cgi?id=1908515 but it's not clear that this is the same issue.

**Comment by christian-bromann** [comment]
Thanks all, I will make sure to post in the right platforms next time!

**Comment by christian-bromann** [comment]
I have commented on the bugzilla bug linked above.
