### ISSUE TITLE
input.Key{Down,Up}Action `value` is undefined

### ISSUE THREAD

**Issue by martinpitt** [w3c/webdriver-bidi#757]
[input.performActions](https://w3c.github.io/webdriver-bidi/#command-input-performActions) allows you to simulate key presses. E.g. typing an "a":

```py
actions=[
        {"type": "key", "id": "key-0", "actions": [
        {"type": "keyDown", "value": "a"},
        {"type": "keyUp", "value": "a"}
]}])
```

The documentation currently just says `value: text` without any further explanation/definition.

With Chromium 126.0.6478.182 (as packaged in Fedora  40), supplying e.g. "hello" does not work:

> bidi.WebdriverError: error: Invalid key value: hello

Now, that's fair -- I *expected* this to describe a single key, not  series of keys. But curiously it *does* work with Firefox 128.0 (also as packaged in Fedora 40), and it succeeds typing "hello" into the web page.

My bigger concern is actually how to do non-ASCII keys. With [CDP's Input.dispatchKeyEvent()](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent) you could press keys like `ArrowLeft`, `Enter` or `Delete`. But again with Chromium that just fails with

> bidi.WebdriverError: error: Invalid key value: Enter

while with Firefox it types a literal "Enter" word.

So this is underspecified and inconsistent, and there doesn't seem to be a way how to input key names and/or modifiers like "Shift", "Control", and so on.

**Comment by martinpitt** [comment]
It doesn't belong into a bug report, but I have to let it out: I just *love* this spec: https://w3c.github.io/webdriver-bidi . Many thanks for this great work, and getting the browsers united behind it.

We are currently porting [our](https://cockpit-project.org/) tests from CDP to bidi, and it makes things so much more consistent and also easier. This is the only hiccup that I've found so far, and I suppose it's easy enough to work around by just synthesizing a [web platform's KeyBoardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent).

**Comment by martinpitt** [comment]
Thank you, that works. Could https://w3c.github.io/webdriver-bidi/#command-input-performActions link to https://w3c.github.io/webdriver/#keyboard-actions to make that more discoverable?

**Comment by whimboo** [comment]
@martinpitt would you mind filing a bug against Firefox? You can use [this URL](https://bugzilla.mozilla.org/enter_bug.cgi?product=Remote%20Protocol&component=WebDriver%20BiDi). Thanks.

Should we then close this issue?

**Comment by martinpitt** [comment]
@whimboo Right, retitling accordingly. Indeed just adding that link to the classic spec would help a lot to understand the "value" field.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1910352 about that multi-character quirk.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/760
