### ISSUE TITLE
Root node for `browsingContext.locateNodes` is not defined an differs between Chrome and Firefox

### ISSUE THREAD

**Issue by christian-bromann** [w3c/webdriver-bidi#764]
## Expected Behavior

If I call `browsingContext.locateNodes` with the following parameters:

```
{
  "locator": {"type":"css","value":"*"},
  "context":"4ab66b36-ae31-4c38-90bb-40d97bd48b36"
}
```

I would expect that it would fetch the `<head /> tag as it is the first element in the DOM tree.

## Actual Behavior

__Firefox:__ ✅ works as expected and returns

```
{
    "nodes": [
        {
            "type": "node",
            "sharedId": "d2030884-983d-45f9-85fd-10552d1e9f70",
            "value": {
                "nodeType": 1,
                "localName": "head",
                "namespaceURI": "http://www.w3.org/1999/xhtml",
                "childNodeCount": 0,
                "attributes": {},
                "shadowRoot": null
            }
        },
        {
            "type": "node",
            "sharedId": "9d66bb03-20fd-4e5d-bacf-68bbdda1d15d",
            "value": {
                "nodeType": 1,
                "localName": "body",
                "namespaceURI": "http://www.w3.org/1999/xhtml",
                "childNodeCount": 0,
                "attributes": {},
                "shadowRoot": null
            }
        }
    ]
}
```

__Chrome:__ ❌ fails even though `*` is a valid selector and returns

```ts
{
    "nodes": []
}
```

## Reproducible Example

See https://github.com/christian-bromann/bidi-locateNodes-error, clone the repo, install dependencies, and call `npm run wdio`

**Comment by whimboo** [comment]
Looks like that this issue is exactly about the problem that I've fixed on https://github.com/w3c/webdriver-bidi/pull/1090. So it was a bug in our specification and implementation.
